### ISSUE TITLE
Documentation Doesn't State Supported ZFS Versions

### ISSUE THREAD

**Issue by ahmad-alwazzan** [psy0rz/zfs_autobackup#10]
Hi psy0rz,

I would like to comment that the documentation does not state which OSes or ZFS versions are supported, I tried to run this on Solaris and Linux to see if it works. main issue is that some commands like 'zfs get -t filesystem,volume...' don't exist of those versions on ZFS.

thanks

**Comment by psy0rz** [comment]
It should work with all recent zfs versions. However it cant test it with solaris.

I am using it with smartos which is a (open)solaris derivative.

Can you paste some of the error when you run it with --debug?

**Comment by psy0rz** [comment]
please reopen if you have more information.
