### ISSUE TITLE
Different thinning policy on the replication target

### ISSUE THREAD

**Issue by MarkusLohmayer** [psy0rz/zfs_autobackup#104]
I am wondering if it is possible to set a different thinning schedule on the replication target.

Of course, the motivation behind this question is that the backup server which receives the snapshots might have less storage capacity than the source system and an obvious way to deal with this problem is to thin more aggressively on the target.
It also seems sort of okay to do so since the source system already works with ZFS mirrors and replication to the target is only done to recover the server in case it burned down or something similar.

**Comment by fnickander** [comment]
> I am wondering if it is possible to set a different thinning schedule on the replication target.

Unless I misunderstand your question, this can be achieved by using different thinning schedules with `--keep-source` and `--keep-target`

```
--keep-source SCHEDULE
                        Thinning schedule for old source snapshots. Default:
                        10,1d1w,1w1m,1m1y
--keep-target SCHEDULE
                        Thinning schedule for old target snapshots. Default:
                        10,1d1w,1w1m,1m1y
```

**Comment by MarkusLohmayer** [comment]
@fnickander Thank you! I am sorry for not properly studying the documentation. I will close the issue.
