### ISSUE TITLE
Usage as non-root

### ISSUE THREAD

**Issue by norsemanGrey** [psy0rz/zfs_autobackup#108]
Is it possible to set this up to work as a non-root user? I got it partially to work by giving the users on both source and target permissions with `zfs allow`, but it keeps failing on transfer as it cannot mount filesystems being created on target. I believe this is an issue with ZFS under Linux, but mounting should not really be required for sending snapshots for a backup. I can always mount later if required.

`! [Target] STDERR > filesystem successfully created, but it may only be mounted by root`

**Comment by psy0rz** [comment]
Can you try with `--clear-mountpoint ` ?

This should prevent mounting and is recommended in general.

**Comment by psy0rz** [comment]
reopen it if you still have problems.

**Comment by psy0rz** [comment]
it already uses zfs recv -u, so it shouldnt even try to mount it right away.

Which version of zfs-autobackup are you using? Try upgrading to the latest stable version.

> pip install --upgrade zfs-autobackup

**Comment by norsemanGrey** [comment]
> it already uses zfs recv -u, so it shouldnt even try to mount it right away.
> 
> Which version of zfs-autobackup are you using? Try upgrading to the latest stable version:

I am using version 3.1.1. Lookin closer at this there is actually only a problem if it has to create a filesystem more than one level deep. Not sure what is going on, but it is probably due to my limited experience with ZFS. 

Lets say I am using zfs-autobackup  to take a snapshot of **rpool/test/temp/folder_1** on computer_1 to **rpool/backup/computer_1** on computer_2.  It will create and mount **rpool/backup/computer_1/test** the first time I run it, and give me an error that it cannot create/mount **rpool/backup/computer_1/test/temp**. The next time I run it it will create and mount **rpool/backup/computer_1/test/temp** and give me an error that it cannot create/mount **rpool/backup/computer_1/test/temp/folder_1**. The Third time it will create and mount **rpool/backup/computer_1/test/temp/folder_1**.

**Comment by psy0rz** [comment]
ah its probably because it tries to create the parent. maybe you can try to create the parent dataset first. you probably only have to do that once.

**Comment by norsemanGrey** [comment]
Yes that works for sure. I am just surprised that there are permission issues with creating/mounting the children filesystem and not the "top-level" parent. Is this related inherently to some way ZFS works or is it to do with how zfs-autobackup creates the parent datasets?

**Comment by psy0rz** [comment]
Yes, this can be seen a bug i think. Received filesystems are not mounted by default (zfs recv -u), however if it create a parent it just use zfs create without the -u flag.

So this is inconsitent and needs to be changed.

Also it would be confusing if a receive is without mounting, while after a reboot it will  mount. (if --clear-mountpoint is omitted)

Ill create an issue for this and fix it. In the mean time you know how to work around it.

**Comment by norsemanGrey** [comment]
Awesome, thanks for looking into it!

**Comment by norsemanGrey** [comment]
Btw. an observation on something that is somewhat related: When setting the --clear-mountpoint flag the backed-up filesystem mountpoint is kept the same as the original instead of changing it to the target mountpoint location. Not sure if this is by design? I understand the flag is set to prevent the target server from mounting in case of mount conflicts, but would it not be more natural to change the mountpoint in case you do want to mount it manually later?

**Comment by psy0rz** [comment]
Since its a backup I want keep as many properties as possible.  At the time i didnt knew of the zfs inherit -S flag yet. (or didnt it exist?)

With that -S option you can always restore the property to the originally received value. 

So I think --filter-properties=mountpoint is a much better alternative to --clear-mountpoint. That way it will mount stuff that was mounted, but in a logical location. (same as dataset name)

This should be documented better, and --clear-mountpoint should be deprecated. And received datasets that have canmount=noauto should not be mounted.

**Comment by psy0rz** [comment]
i looked it up: https://github.com/openzfs/zfs/commit/0bf8501

the zfs inherit -S flagi wasnt documented until 7 years ago, around the time i started coding with zfs-autobackup. (and it probably took a while before it was in smartos, which i then used most i think)
