### ISSUE TITLE
Question: Use for Local Backup

### ISSUE THREAD

**Issue by norsemanGrey** [psy0rz/zfs_autobackup#111]
Just begun using it and this is an awesome tool. Thanks!

Just wondering though (maybe I have missed it from the documentation); how do you use it for local backup? Is it as easy as skipping the --ssh parameters?

**Comment by psy0rz** [comment]
yep, easy as that :)

if you're unsure, just run it with --test to see what it would do.

**Comment by norsemanGrey** [comment]
Terrific! thanks for the quick reply :)
