### ISSUE TITLE
More consistent mounting

### ISSUE THREAD

**Issue by psy0rz** [psy0rz/zfs_autobackup#112]
See #108 

* zfs create doesnt use the -u flag
* zfs recv DOES use the -u flag

I think we should mount a received filesystem only if canmount=on and it has a mountpoint, as to make that part consistent behaviour. ( and make it keep in mind --clear-mountpoint  as well)

Not sure what to do with created parents yet. (mounting a parent may invoke changes on an even higher parent since it will create the mountpoint as well)

**Comment by psy0rz** [comment]
also we should update the documentation to explain that clear-mountpoint will result in either:

- a directory getting created in the parent dataset, thus creating a change. (needing a rollback or --force)
- a "failed to create mountpoint: Read-only file system" if the parent dataset is readonly. (which is usually recommented)

**Comment by psy0rz** [comment]
i made some pretty big changes:

-  when we need to create empty parent datasets, they now have canmount=off. this is hopefully less annoying and more consistent.
- after an initial transfer we now simulate an "zfs mount -a" for that specific dataset, so that behaviour is consistent with a reboot.

since this is pretty different behaviour, i think this warrants a major release version.

**Comment by psy0rz** [comment]
(also broke some stuff)

**Comment by psy0rz** [comment]
documentation at https://github.com/psy0rz/zfs_autobackup/wiki/Mounting

**Comment by exptom** [comment]
@psy0rz any ETA on when this might make it into a release? I'm hitting issues with doing non-root backups and the parent datasets throwing an error because they are defaulting to `canmount=on` when created by zfs-autobackup

**Comment by psy0rz** [comment]
please try https://github.com/psy0rz/zfs_autobackup/releases/tag/untagged-d1ec24f49a10c76951fe

**Comment by psy0rz** [comment]
i'll try to release 3.3 beta soon, which has this feature.
