### ISSUE TITLE
zfs_autobackup_option_test does not exist

### ISSUE THREAD

**Issue by GijsVermarien** [psy0rz/zfs_autobackup#117]
For some reason there seems to be something up with zfs_autobackup_option_test? In the end the transfer fails. What could this have to do with? 

I am using the flags: `--progress --verbose --clear-mountpoint --debug-output`

And the debug output is:

```
# [Source] CMD    > (ssh username@target_ip 'zfs send -L zfs_autobackup_option_test')
# [Source] STDERR > cannot open 'zfs_autobackup_option_test': dataset does not exist
# [Source] EXIT   > 1
# [Source] CMD    > (ssh username@target_ip 'zfs send -e zfs_autobackup_option_test')
# [Source] STDERR > cannot open 'zfs_autobackup_option_test': dataset does not exist
# [Source] EXIT   > 1
# [Source] CMD    > (ssh username@target_ip 'zfs send -c zfs_autobackup_option_test')
# [Source] STDERR > cannot open 'zfs_autobackup_option_test': dataset does not exist
# [Source] EXIT   > 1
# [Target] CMD    > (zfs recv -s zfs_autobackup_option_test)
# [Target] STDERR > cannot receive: failed to read from stream
# [Target] EXIT   > 1
# [Target] pool/dataset/home@offsite-20220209090005: Enabled resume support
# [Target] CMD    > (ssh username@target_ip 'zfs send --large-block --embed --verbose --parsable --props homepool/home@offsite-20220209090005') | (zfs recv -u -o canmount=noauto -v -s pool/dataset/home)
# [Source] STDERR > full	homepool/home@offsite-20220209090005	168837677848
# [Source] STDERR > size	168837677848
# [Source] EXIT   > 0
# [Target] EXIT   > 0
# [Target] pool/dataset/home@offsite-20220209090005: Checking if filesystem exists
# [Target] CMD    > (zfs list pool/dataset/home@offsite-20220209090005)
# [Target] STDERR > cannot open 'pool/dataset/home@offsite-20220209090005': dataset does not exist
# [Target] EXIT   > 1
! [Target] pool/dataset/home@offsite-20220209090005: error during transfer
! [Source] homepool/home: FAILED: Target doesn't exist after transfer, something went wrong.
! Exception: Target doesn't exist 
```

**Comment by psy0rz** [comment]
nope , this just used to see which options are supported by the zfs command, you can ignore those errors. (they are hidden in debug mode for that reason, errors that matter are colored red.

Did you use the strip-path option? I think you've stripped too much or need to destroy pool/dataset/home.

**Comment by psy0rz** [comment]
the new version will probably give you a much clearer idea of whats going on.

**Comment by psy0rz** [comment]
You can install and try it with:

> pip install zfs-autobackup==v3.1.2-rc1

**Comment by GijsVermarien** [comment]
Will give it a go and let you know. Have not had the chance to try it again after creating my issue (which is never a good thing with backups obviously...)

**Comment by psy0rz** [comment]
Also if you want "1:1 replication", in which case you sync your entire source pool to a target pool and keeping the path-structure, try rc2

And checkout the new documentation: https://github.com/psy0rz/zfs_autobackup/wiki#stripping-the-path
