### ISSUE TITLE
No argument for non-standard SSH port

### ISSUE THREAD

**Issue by HaTaX2** [psy0rz/zfs_autobackup#12]
It would be nice to have an additional argument to handle SSH over a port other than the standard 22.  Something like '--ssh-port' that would be utilized by both '--ssh-target' and '--ssh-source' would be perfect.

**Comment by psy0rz** [comment]
Please look in the manual for the clean way to do this: https://github.com/psy0rz/zfs_autobackup#specifying-ssh-port-or-options

**Comment by HaTaX2** [comment]
I'm blind, sorry for not doing a better job reading the readme!

**Comment by psy0rz** [comment]
No problem. I'm glad you're using it. :)
