### ISSUE TITLE
TCP tuning suggestion

### ISSUE THREAD

**Issue by xrobau** [psy0rz/zfs_autobackup#120]
I'm not sure if you want to actually put this into the README.md, so I thought I'd mention it here.

By default, the linux kernel uses `cubic` as the TCP Congestion Control protocol. This is extremely good for _almost_ all situations, except for moving huge amounts of data over the public internet where you can have brief bursts of congestion (and therefore packet loss).

Changing this to `scaleable` makes TCP sessions recover much faster from packet loss, and return to the full speed available without the extended recovery of the normal `cubic` protocol.

I suggest you add this as a suggestion if people are sending data over the internet:

/etc/sysctl.d/60-send-bulk-tcp.conf:
```
# Recovers rapidly from congestion
net.ipv4.tcp_congestion_control = scalable
```

https://en.wikipedia.org/wiki/Scalable_TCP

**Comment by psy0rz** [comment]
thanks, ill add it to the performance tips.

**Comment by psy0rz** [comment]
done
