### ISSUE TITLE
Completely destroy source snapshots and parent dataset

### ISSUE THREAD

**Issue by eisengrau** [psy0rz/zfs_autobackup#122]
Hello,

I have two proxmox hosts, one is source and another is target. I have backed up the required datasets from source to target. Now I want to destroy the relevant datasets from the "source", since this machine is yet to be decomissioned, and the primary source of data would be "target" only, which will be the new source of replication to a new host later on...

The problem is, that there is seemingly no way to destroy a dataset recursively from the source, as it looks like zfs-autobackup "takes ownership" of the most recent snapshot (and only, after thinning). The OS lists that the dataset is busy, even after zfs unmounting it.

I have also tried to remove the label from the dataset, with for ex. "zfs set autobackup:offsite2=- mypool/mydataset2" but I still can't do "zfs destroy mypool/mydataset2@mostrecent snapshot".

One note is that zfs-autobackup is not installed on the "source" machine. I only did "pulls" from the target machine directly with zfs-autobackup.

Is there a proper way to "decomission the backup system"  (of the already copied datasets and snapshots) from a source machine? Or a reboot is needed after removing the aformentioned "autobackup:" labels?

**Comment by psy0rz** [comment]
It uses zfs hold to hold a dataset. This is to prevent accidental deletion of the common snapshot.

You can either release the hold, but it might be easier to delete the whole zpool with zpool destroy.
