### ISSUE TITLE
--other-snapshots never get deleted

### ISSUE THREAD

**Issue by cblank2** [psy0rz/zfs_autobackup#129]
Hi,
i love it. I'm using it for a few months now (since i use zfs) and it works pretty well.
But it seems, that the snapshots created by zsys (ubuntu 21.10) are sent to target (with --other-snapshots) but are never deleted on target.
On the source system i have about 50 snapshots for a user dataset, on the target i have 1115 snapshots for the same dataset.

- would they be delete with --destroy-missing? (which seem to be for a different case)
- should i omit the --other-snapshots flag? would it still send all the data to target (all data since the last zfs_autobackup-snapshot (not only since the last zsys-snapshot)?

I think an option like --delete-other-snapshots (which simply deletes the other snapshots on the target, if they are deleted on the source) would be my preferred way to handle this.

I'm using this command:
zfs-autobackup --ssh-target server1 --keep-source 10,1d1w,1w1m,1m1y --keep-target 10,1d1w,1w1m,1m1y --other-snapshots --strip-path 1 --clear-refreservation --clear-mountpoint --zfs-compressed  --set-properties readonly=on --no-holds --allow-empty --verbose --progress  mybackup dpool/backups/...

zfs-autobackup v3.2-dev1 - (c)2021 E.H.Eefting (edwin@datux.nl)

Thank you
Christian

**Comment by psy0rz** [comment]
That is correct: As per documentation, zfs-autobackup can not destroy other snapshots, to prevent catastrophes. :)

In your case (and most cases) you dont need --other-snapshots, just omit it. It will always send all the data, just less granular. If you need more snapshots, just adjust the schedule.

So: A snapshot always points to all the data at that point in time, of that specific dataset. (filesystem or zvol) More snapshots are useful if you want to be able to access more points in time.

To get rid of the other snapshots manually use some unix magic:

Get a list of just snapshot names of a pool (no headers and other info):

```
# zfs list -H -r -t snapshot -o name rpool
```

Filter the stuff you want to get rid of:
```
zfs list -H -r -t snapshot -o name rpool | grep @somename
```

The dangerous step, so check the output of the previous command.

This will delete all the snapshots that the previous line outputted:
```
zfs list -H -r -t snapshot -o name rpool | grep @somename | xargs -n1 -i  zfs destroy "{}"
```

Dont forget the -i and quotes and {} .

**Comment by cblank2** [comment]
Thank you for you very complete answer - this helped!

**Comment by psy0rz** [comment]
youre welcome :)
