### ISSUE TITLE
Incremental Backup on usb?

### ISSUE THREAD

**Issue by killmasta93** [psy0rz/zfs_autobackup#13]
Hi,
I was looking to find a way to backup to the USB but on the -help commands could not find the option is this script possible to backup incremental on a usb?
Thank you

**Comment by psy0rz** [comment]
Yes, but this backup system is only to make backups from and to ZFS filesystems.

You would have to format your usbstick with a ZFS filesystem. Then you can just specify that filesystem as the target path.

**Comment by killmasta93** [comment]
Thanks for the reply, i tried running the following but could not find on the commands 

`./zfs_autobackup rpool/data/vm-117-disk-0 | usb/baks
`
This is my pool
`root@prometheus2:~/zfs_autobackup# zpool status
  pool: rpool
 state: ONLINE
  scan: scrub repaired 0B in 5h38m with 0 errors on Sun Oct 13 06:02:36 2019
config:

	NAME        STATE     READ WRITE CKSUM
	rpool       ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    sda3    ONLINE       0     0     0
	    sdb3    ONLINE       0     0     0

errors: No known data errors

  pool: usb
 state: ONLINE
  scan: none requested
config:

	NAME        STATE     READ WRITE CKSUM
	usb         ONLINE       0     0     0
	  baks      ONLINE       0     0     0
`

**Comment by psy0rz** [comment]
It doesn't seem you know how unix works. You cant pipeline something to a filesystem like that.

Something like this perhaps:

./zfs_autobackup yourbackupname rpool/data/vm-117-disk-0
