### ISSUE TITLE
Generate Metadata and Python 3?

### ISSUE THREAD

**Issue by tanhueco** [psy0rz/zfs_autobackup#14]
Nice script.  

For SmartOS setups, it will be wonderful if the script also generate the metadata (json) file and send it together with the backup files for close to full automation.

Also, can it be updated to Python 3+ since repositories nowadays defaults to Python 3?

**Comment by psy0rz** [comment]
Python 2 and 3 now both are supported: https://github.com/psy0rz/zfs_autobackup/releases/tag/v3.0-beta1

I think the zone-data you need is in /etc/zones, and is already backupped if you set the autobackup:... property on zones.
