### ISSUE TITLE
"Analysing missing" also analyses datasets that do not belong to backup

### ISSUE THREAD

**Issue by digitalsignalperson** [psy0rz/zfs_autobackup#149]
If I'm syncing a single dataset, the part the takes the longest doing nothing is "Analyzing missing 1/13" ... "2/13" ... "3/13" ....

e.g. ~9 seconds of just analyzing 13 datasets which none of are part of the selection.

I'm not sure what what analysis is required since it should not be looking at datasets without the autosnapshot:whatever selection property. Or is querying that prop what is slow?

One workaround could be.

```
if not self.args.no_thinning:
    self.thin_missing_targets(target_dataset=target_path_dataset, used_target_datasets=target_datasets)
```

to

```
if not self.args.no_thinning_missing_targets:
    self.thin_missing_targets(target_dataset=target_path_dataset, used_target_datasets=target_datasets)
```

with a new option for --no-thinning-missing-targets.

Any thoughts?

**Comment by psy0rz** [comment]
sounds good, but call it --no-thinning-missing.

and dont forget the "or --no-thinning", since that always should mean no thinning at all.

this is also the reason i added progress reporting, since i have some very slow pools that took long doing unknown stuff :)

**Comment by psy0rz** [comment]
in your case the slow part is that its getting a list of snapshots for every target dataset thats missing on the source. (and maybe it tries to get the properties as well)

--debug will show what its actually doing.

**Comment by digitalsignalperson** [comment]
so it seems to just be  just the ssh calls soaking up the time

if each missing dataset is doing e.g.

```
# [Target] rpoolx/DATA/thunderbird: Missing on source, thinning
# [Target] rpoolx/DATA/thunderbird: Checking if filesystem exists
# [Target] CMD    > (ssh root@workstation 'zfs list rpoolx/DATA/thunderbird')
# [Target] rpoolx/DATA/thunderbird: Getting snapshots
# [Target] CMD    > (ssh root@workstation 'zfs list -d 1 -r -t snapshot -H -o name rpoolx/DATA/thunderbird')
```

Those commands are on the order of 10msec locally, and ~250msec over ssh. So at least half a second a pop, times e.g. 13 in my case.

Though I am confused why it is trying to thin datasets that don't have the autobackup:blah selection property in `def thin_missing_targets`. This is different to local thinning where it definitely only tries to thin the datasets that have autobackup:blah

**Comment by psy0rz** [comment]
I have to look in to it, it should indeed only have to list/thin snapshots in the target path that belong to the correct  backup.

If it doesnt, i would be slow in cases like yours. (on the other hand: fetching properties of a dataset can be slow as well)

Note that it still wont destroy any snapshots that dont belong the backup, so its not a direct problem.

**Comment by digitalsignalperson** [comment]
>  it should indeed only have to list/thin snapshots in the target path that belong to the correct backup.

from my understanding `source_dataset.sync_snapshots(...)` does that, and I see in the `def _plan_sync` how it generates the source_obsoletes and target_obsoletes lists as expected based on `self.our_snapshots`

However the call to `self.thin_missing_targets(...)` explicitly tries to thin each target dataset that was not part of the just synced datasets with ` [dataset for dataset in target_dataset.recursive_datasets if dataset not in used_target_datasets]`

> Note that it still wont destroy any snapshots that dont belong the backup, so its not a direct problem.

There is a potential to destroy snapshots you wanted to keep if you used a snapshot format independent of the selection property name (i.e. drop the {} from the format), but maybe that is "off label" use

**Comment by psy0rz** [comment]
in that case the loop needs an extra if-statement that checks for if the correct autobackup:property is set.

**Comment by digitalsignalperson** [comment]
Hmm maybe it isn't a bug depending on your assumptions. It would be relying on the `self.zfs_node.snapshot_time_format` in `def timestamp` to find the selection property through the timestamp format. The `def is_ours` always does `try: self.timestamp` rather than explicitly look up the zfs property. Maybe that is sensible and only breaks in the pathological case I describe of excluding "{}" from the snapshot format. 

In my case I actually am not including "{}" in the snapshot format because I am trying to manage multiple sources/targets and keep all the snapshots in the same thinning group.  I would get the expected behaviour with a `--no-thinning-missing-targets`

**Comment by psy0rz** [comment]
i've looked into it: It only thins missing datasets that are under the target-path and it only destroys snapshots that are according to the formatting/name of the backup.
