### ISSUE TITLE
Can't do local-only snapshots if dataset is received

### ISSUE THREAD

**Issue by digitalsignalperson** [psy0rz/zfs_autobackup#150]
If I just want to snapshot and thin locally, e.g.

```
zfs-autobackup -v --keep-source 5,1min5min testdata
```

I'm running into 
```
  #### Selecting
  NOTE: Source and target are on the same host, excluding received datasets from selection.
  [Source] fpool/testdata: Excluded (dataset already received)
! No source filesystems selected, please do a 'zfs set autobackup:testdata=true' on the source datasets you want to select.
```

when I have previously received the dataset

```
NAME                                                  PROPERTY             VALUE                SOURCE
fpool/testdata                                        autobackup:testdata  true                 received
```

But I actually do want to snapshot and thin it.

**Comment by digitalsignalperson** [comment]
I can work around by using `--set-properties autobackup:testdata=true` to always make source local on received, independent of this local-only snapshot command.

**Comment by psy0rz** [comment]
this is has to do with the use case of local backups work and how zfs-autobackup should determine what datasets are source or target.

**Comment by psy0rz** [comment]
if think if your specify a --ssh-target, which can be any random host since its not used, youll be fine

**Comment by psy0rz** [comment]
well i couldnt think of anything better than to add an --include-received option to overule this behaviour.

(generally most users want the automatic enabling of --exclude-received, so we let it in for now)

**Comment by psy0rz** [comment]
this probably wont be an issue anymore in v3.4: we now filter the autobackup: property to prevent confusion.
