### ISSUE TITLE
issues trying to push to a QNAP device

### ISSUE THREAD

**Issue by digitalsignalperson** [psy0rz/zfs_autobackup#170]
I'm trying to do a zero-trust push+pull config from an ubuntu 20.04 zfs-0.8.3 system, to a QNAP NAS with "QuTS hero h5.0.0.2120".

Funny no matter what command I try on the QNAP, it will not tell me a zfs version.
`/sys/module/zfs/version` doesn't exist
`dmesg` not showing any version info
`zpool upgrade -v`  lists features but no version
`zpool get version zpool1` gives

```
NAME    PROPERTY  VALUE    SOURCE
zpool1  version   -        default
```

anyway, trying to use a "test" group

```
zfs-autobackup -v -d \
    --ssh-source ubuntu@the-source-system \
    --ssh-target admin@the-qnap-system \
    --keep-source 4 \
    --keep-target 4 \
    --no-holds \
    --min-change 1 \
    --snapshot-format "{}-%Y-%m-%d-%H%M" \
    --strip-path=0 \
    test zpool1/backups
```

I get as far as 

```
  [Target] zpool1/backups/data/test@test-2022-10-17-2310: receiving full
# [Target] CMD    > (ssh admin@the-qnap-system 'zfs recv -s zfs_autobackup_option_test')
# [Target] STDERR > invalid option 's'
# [Target] STDERR > usage:
# [Target] STDERR >     receive [-vnFuk] <filesystem|volume|snapshot>
# [Target] STDERR >     receive [-vnFuk] [-d | -e] <filesystem>
! [Target] Command "ssh admin@the-qnap-system 'zfs recv -s zfs_autobackup_option_test'" returned exit code 2 (valid codes: [0, 1])
# [Target] CMD    > (ssh ubuntu@the-source-system 'zfs send --verbose --parsable --props data/test@test-2022-10-17-2310') | (ssh admin@the-qnap-system 'zfs recv -u -v zpool1/backups/data/test')
# [Source] STDERR > full        data/test@test-2022-10-17-2310        43632
! [Target] STDERR > cannot receive new filesystem stream: cannot match drr_type DRR_VERSION.
# [Source] STDERR > size        43632
! [Target] Command "ssh admin@the-qnap-system 'zfs recv -u -v zpool1/backups/data/test'" returned exit code 1 (valid codes: [0])
! [Source] data/test: FAILED: Last command returned error
! Exception: Last command returned error
```

with `invalid option 's'` for `zfs recv` as well as `cannot receive new filesystem stream: cannot match drr_type DRR_VERSION`

Any signs of this being an issue on the zfs_autobackup side? Haven't found much luck with googling that drr_type error message

**Comment by psy0rz** [comment]
Indeed no google hits on even parts of that zfs error. Hopefully someone here knows, otherwise ask on r/zfs or stackoverflow?

Or file an issue on openzfs github.

**Comment by psy0rz** [comment]
found at least some stuff for ddr_type: https://github.com/openzfs/zfs/issues?q=+drr_type

**Comment by psy0rz** [comment]
so, you're probably using some kind of too new feature in the dataset you're trying to send, since qnap's zfs version is probably much older.

**Comment by digitalsignalperson** [comment]
thanks I'll have to try creating some test pools/datasets with limited features to see if anything can be received...

**Comment by psy0rz** [comment]
ill close this, since its a ZFS issue, unrelated to zfs-autobackup i think.
