### ISSUE TITLE
pre/post hooks, typically for databases

### ISSUE THREAD

**Issue by gczuczy** [psy0rz/zfs_autobackup#171]
Hello,

Could you please add some pre and post snapshot hooks, as these are typically required for databases?
For an example postgresql has pg_backup_(start|stop) to call before you take your snapshot:
https://www.postgresql.org/docs/current/continuous-archiving.html#BACKUP-BASE-BACKUP

Mariadb has flush with locks (filesystem level section): https://mariadb.com/kb/en/backup-and-restore-overview/

Also, mariadb is a bit problematic, because the session which did the flush with locks has to be kept open during the snapshot creation, and the unlock has to be issued in the very same session.

So, in order to consistently snapshot DBs, such a hook is needed, otherwise the data will most probably be inconsistent, and the whole process is pointless.

**Comment by psy0rz** [comment]
we already have this :)

https://github.com/psy0rz/zfs_autobackup/wiki/PrePost

**Comment by gczuczy** [comment]
Ahh, that's quite cool. Sorry, I was following the quickstart guide, and checked the help, but haven't spotted it.

Btw, the -v as shown in the quickstart doesn't work on 3.1, it's not recognizing the option.

**Comment by psy0rz** [comment]
you need 3.1.3 for that
