### ISSUE TITLE
Crontab: exit code 127

### ISSUE THREAD

**Issue by tiagogbarbosa** [psy0rz/zfs_autobackup#179]
When running from cron i got this error

```
#### Target settings
  [Target] Datasets are local
  [Target] Keep the last 4 snapshots.
  [Target] Keep every 1 day, delete after 1 week.
  [Target] Keep every 1 week, delete after 1 month.
  [Target] Receive datasets under: xxx/xxx

  #### Synchronising
! [Target] Command "zfs list xxx/xxx" returned exit code 127 (valid codes: [0, 1])

```

Running "manual"  from terminal no error occur..
Any ideas?

**Comment by psy0rz** [comment]
This means the zfs command isnt in the PATH during the crontab execution.

Usually you can put something like PATH=$PATH:/usr/bin in front of the command. 

To find out the path of a command use:
```
which zfs
```

**Comment by psy0rz** [comment]
Also you can add 2>&1 to the command to see the actual errors as well, in your crontab:
```
zfs-autobackup .... 2>&1
```

**Comment by tiagogbarbosa** [comment]
Thank you!

**Comment by gitthangbaby** [comment]
In my case, i simply didn't have zfs on target system, which I thought wasn't requirement.
