### ISSUE TITLE
Rate setting question

### ISSUE THREAD

**Issue by Simon4711** [psy0rz/zfs_autobackup#184]
Just wanted to proof that the rate setting for my setup is o.k. But often the real rate shown in Proxmox network traffic is much higher than my rate setting, maybe I have to use another input for that field? My setting is **25M**, but it seems that it's pumping with 100% of the wan line capa. The real line capa is maximum 300MBit/s, and Proxmox shows me 27,6 MB in the network traffic chart. 

flock -n /var/dusham.lock /usr/local/bin/zfs-autobackup -v --ssh-source pvezfsdus dusham rpool/crypt --pre-snapshot-cmd "qm guest cmd 100 fsfreeze-freeze" --post-snapshot-cmd "qm guest cmd 100 fsfreeze-thaw" --decrypt --encrypt --keep-source=1 --keep-target=2 **--rate 25M -**-buffer 256M --compress > /mnt/pve/proxmox....

**Comment by Simon4711** [comment]
It's o.k. It's just a metering thing in Proxmox.

**Comment by psy0rz** [comment]
ok thx
