### ISSUE TITLE
Getting started states you need root access across servers, you do not.

### ISSUE THREAD

**Issue by stephenhouser** [psy0rz/zfs_autobackup#186]
The getting started guide states: "With a pull backup, the target machine will have root access to the source machine."

The `zfs allow` will allow you to grant `send, snapshot, hold` and other required permissions on a dataset. Thus not requiring "root access to the source machine." You can grant those to any account on the source machine.

**Comment by psy0rz** [comment]
you are right, but then you make sure your user has write access to /dev/zfs as well.

i'll update the documentation to reflect this, thanks

**Comment by psy0rz** [comment]
I added a note https://github.com/psy0rz/zfs_autobackup/wiki#setup-ssh-login and i changed that text to 'ssh access' instead of 'root access'

**Comment by stephenhouser** [comment]
In setting up, the account will need `destroy,hold,mount,release,send,snapshot` as in:
```bash
zfs allow USER destroy,hold,mount,release,send,snapshot tank/dataset`
```
