### ISSUE TITLE
pip install yields two versions "zfs-autobackup" and "zfs_autobackup"

### ISSUE THREAD

**Issue by fermulator** [psy0rz/zfs_autobackup#19]
```
$ sudo -H pip install zfs-autobackup
Requirement already satisfied: zfs-autobackup in /usr/local/lib/python3.6/dist-packages (3.0rc3)
Requirement already satisfied: argparse in /usr/local/lib/python3.6/dist-packages (from zfs-autobackup) (1.4.0)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from zfs-autobackup) (0.3.7)
```

now to see the tab-complete
```
$ zfs
zfs             zfs_autobackup  zfs-autobackup  
```

hm,
```
$ which zfs_autobackup
/usr/local/bin/zfs_autobackup

$ which zfs-autobackup
/usr/local/bin/zfs-autobackup
```

```
$ ll /usr/local/bin | grep zfs
-rwxr-xr-x  1 root root 53903 Feb 19 20:37 zfs_autobackup*
-rwxr-xr-x  1 root root 53903 Feb 19 20:37 zfs-autobackup*
```

Looks like _duplicate_ executable scripts
```
$ file /usr/local/bin/zfs_autobackup
/usr/local/bin/zfs_autobackup: Python script, ASCII text executable, with very long lines
$ file /usr/local/bin/zfs-autobackup
/usr/local/bin/zfs-autobackup: Python script, ASCII text executable, with very long lines
```

**Comment by fermulator** [comment]
indeed,
https://github.com/psy0rz/zfs_autobackup/blob/v3/setup.py#L17

what is the reason for the duplication? this is confusing to users I'd suggest; (it certainly caught me off guard) - which one to use? (pretty sure it doesn't matter which one)

ideally we kill this duplication (and figure pip upgrades clean up the stale one)

if there is a good reason for it ... use a symlink instead?

**Comment by psy0rz** [comment]
The reason is that the name used to be zfs_autobackup, but i want to change it to zfs-autobackup. However i also want old script to keep working. I tried using a link but it normalized it to a copy.

I'll just remove the _ version, since previously people had to manually install zfs_autobackup anyway.

**Comment by psy0rz** [comment]
fixed in master
