### ISSUE TITLE
Issue with duplicate zfs sends

### ISSUE THREAD

**Issue by florian-obradovic** [psy0rz/zfs_autobackup#194]
Hi and thank you very much the great work.

Unfortunately I'm struggling getting it to work with my use case:
- rpool with properties:
-- autobackup:backup2thunder-970evo
-- autobackup:backup2tank
- thunder-970evo pool as first target
- tank/encrptd/zfs-autobackup as second target

I want to backup my rpool to thunderbolt ssd (thunder-970evo) and also to a second pool.
If I understand it correctly I need to create to groups backup2thunder-970evo & backup2tank.

My problem now is that zfs-autobackup wants to copy received datasets on thunder-970evo (with autobackup:backup2thunder-970evo) to my tank as well because the property backup2tank has been sent to thunder-970evo:

![CleanShot 2023-05-22 at 13 05 08@2x](https://github.com/psy0rz/zfs_autobackup/assets/57985125/9935ffb9-7a58-42cd-9720-59d1d230e108)

What could be a solution?
Can we only transfer datasets where property is local / **not received**?

Thanks a lot and best regards!

**Comment by psy0rz** [comment]
Yes, you can use --exclude-received  for that.

Which version of zfs-autobackup do you have? It should normally use that option automaticly if the backup is local. (e.g. if you do not specify ssh-source and ssh-target.)

**Comment by florian-obradovic** [comment]
Awesome, I'm afraid it doesn't work for me by default.
zfs-autobackup --version
zfs-autobackup v3.1.3 - (c)2021 E.H.Eefting (edwin@datux.nl)

I will try the --exclude-received option!

**Comment by florian-obradovic** [comment]
Is the also an option to only send received and don't create new snapshots?

I'd like to pickup all snapshots from tank/encrptd/zfs-autobackup and send them to external usb-disk
