### ISSUE TITLE
Feature Request: show current execution date & time in verbose output

### ISSUE THREAD

**Issue by florian-obradovic** [psy0rz/zfs_autobackup#195]
I'd love to see output of current time and date when running -v verbose which could be very handy with logging, sending e-mails, etc.
![CleanShot 2023-05-22 at 15 34 43@2x](https://github.com/psy0rz/zfs_autobackup/assets/57985125/6031021d-c670-4513-a0c7-b45abf3f2284)

Is this already possible?

**Comment by psy0rz** [comment]
nope but its a usefull option, will include it in a future update. (or make a PR :)
