### ISSUE TITLE
Feature request - Allow one to change mbuffer chunk size.

### ISSUE THREAD

**Issue by P-EB** [psy0rz/zfs_autobackup#203]
Hey,

The default chunk size of 128k for mbuffer is not always ideal. Would it be possible to either make it changeable or to accept a PR with the code modifications?

Cheers!
PEB

**Comment by P-EB** [comment]
Ok I made a PR that seems to do the job and also refines the way mbuffer pipes are added.

**Comment by psy0rz** [comment]
why isnt it always ideal? did you do some tests to different buffer sizes and can i see the results?

**Comment by P-EB** [comment]
Here is a zfs-autobackup with a chunk size of 128k and one with a chunk size of 2k (which I counter-intuitively found to be the best chunk-size in my case after poking rather a lot)

In my case the sending and receiving points are separated by about 500 kms, and multiple network layers I can't change.

2k chunk size
![bkp_2k](https://github.com/psy0rz/zfs_autobackup/assets/3770652/ac011baa-8238-40df-a5c3-f55cd5d6cc87)

128k
![bkp_128K](https://github.com/psy0rz/zfs_autobackup/assets/3770652/1fa9a6f2-9476-443a-89d1-c5e3df27d3c2)

Same origin same destination, same data, same everything. Just a different chunk size.

**Comment by psy0rz** [comment]
ah cool. i think i just randomly decided its 128k , because record size is also 128k or something.

maybe i should omit a default, since then mbuffer will automatically decide it according to page size, which is 4k usually? maybe you can try that as well?

**Comment by P-EB** [comment]
4k was less good in my case. I think your 128k rationale is a good one in general. The flexibility of the argument just seems worthwile for some specific cases.

I'm rerunning my tests I'll try to get you some graphs asap

**Comment by P-EB** [comment]
So, here they are.

Now that I've tweaked my zfs on the receiving side, the perf delta is quite smaller actually (only 8.5%, before it was more like 25 to 30%).

2k
![bkp_2k](https://github.com/psy0rz/zfs_autobackup/assets/3770652/e896cc48-9a0f-44b8-bb07-e615c1acd2ef)

128k
![bkp_128K](https://github.com/psy0rz/zfs_autobackup/assets/3770652/9f54c9d2-c6d0-4f57-a6fe-4451485a2a85)

It's of course reproducible.

**Comment by psy0rz** [comment]
ah nice, thanks for the info!
