### ISSUE TITLE
Please release 3.2 or 3.1.4 or something..

### ISSUE THREAD

**Issue by xrobau** [psy0rz/zfs_autobackup#205]
I just noticed that an issue I solved (and you merged) from 18 months ago still isn't there in the latest build 8-(

Any chance of just releasing 3.2, or a 3.1.4 or something?

**Comment by psy0rz** [comment]
yeah its time :)

**Comment by xrobau** [comment]
I also finally got around to packaging up my auto-replicate stuff, and just stuck it up on github

https://github.com/xrobau/zfs-replicate

Currently it's checking for 3.2b1 https://github.com/xrobau/zfs-replicate/blob/master/roles/replication/tasks/setup.yml#L32 but that should probably switch to 3.2 when it's released for real.

Still haven't written any documentation for it (apart from the example config files), but I'll probably do a PR here - if you don't mind - linking to it, when I have it to a state a normal person could use it 8)

**Comment by psy0rz** [comment]
yeah, i can add a link to the wiki documentation if you're ready :)

**Comment by norsemanGrey** [comment]
Any estimate on the next release? Really looking forward to be able to use the "parent" value :D

**Comment by psy0rz** [comment]
Well the zfs-check stuff has a known issue #176 , but i can create a note for that.

**Comment by psy0rz** [comment]
done..due to a few github annoyances with stuff not being supported anymore, its v3.2.2 at someplaces, but its actuall v3.2 (the pointrelease is only github action stuff thats changed)
