### ISSUE TITLE
Clarifying support for ZFS at rsync.net

### ISSUE THREAD

**Issue by fpga-guy** [psy0rz/zfs_autobackup#220]
I mis-interpreted the [documentation page about using rsync.net](https://github.com/psy0rz/zfs_autobackup/wiki/Backup-to-rsync.net-via-ZFS) based on my understanding that rsync.net uses ZFS for its storage. 

To clarify the page, I think it is important to note that the _ordinary_ service uses ZFS but does not support access via ZFS send/recv. It is not possible to login as the root user on the ordinary service and perform commands to create ZFS datasets or perform ZFS commands like `zfs list`.

The link on the page (_if I had read it_) would have indicated the price for the special ZFS service requires a minimum 5TB quota (about $600/year).  For some that won't be an issue but for me it was a deal breaker.

Consequently, I can't use the excellent `zfs-autobackup` tool you have created with my _ordinary_ rsync.net account and am stuck with plain old rsync. :-(

**Comment by psy0rz** [comment]
Yes you're right, i'll update the page right away.

You can ofcourse also just buy a VM with cheap storage, and install alpine linux for example. super lightweight, and super up-to-date zfs packages.
