### ISSUE TITLE
Add information to the Wiki about how to remove group name

### ISSUE THREAD

**Issue by ddowse** [psy0rz/zfs_autobackup#223]
To remove a obsolete group name e.g ```offsite1``` use ```zfs-inherit(8)``` without a value to the group name.  

```
zfs inherit autobackup:offsite1 rpool
```

This is just a draft. Improve the text to your liking.

**Comment by psy0rz** [comment]
thanks, i added it: https://github.com/psy0rz/zfs_autobackup/wiki#select-filesystems-to-backup
