### ISSUE TITLE
Create actual manual wiki page

### ISSUE THREAD

**Issue by psy0rz** [psy0rz/zfs_autobackup#227]
A page that describes all the options and links to other pages.

#226 reminded me of that

**Comment by danboid** [comment]
I was going to improve your docs for you today only to discover the autobackup "Wiki" page isn't a wiki at all because there is no edit button.

I'm surprised github lets you disable the edit feature on the wiki because then its not actually a wiki any more, its a static web page.

**Comment by danboid** [comment]
The main things I wanted to add was a note about being careful to add exceptions to datasets you don't want to replicate to the `--strip-path` section before running autobackup for real (ie not in --test mode) and I also wanted to add more detail on how autobackup creates and manages its snapshots which might take the form of a section for those coming from z-a-s or sanoid etc.

**Comment by psy0rz** [comment]
Sorry, the problem is that if i open the wiki, everyone can edit it and i wont even get a notification about it.

I'm currently working on a reference manual page that descrips all the steps in detail, so we can add your info to that page perhaps.

**Comment by danboid** [comment]
If you want to vet the docs, move the wiki into the main repo so that users can submit pull requests.

**Comment by psy0rz** [comment]
i've added you to the colleborators, so you can edit pages now

**Comment by danboid** [comment]
Thanks!

**Comment by psy0rz** [comment]
> If you want to vet the docs, move the wiki into the main repo so that users can submit pull requests.

how? will it still look like an intergrated wiki?

please be carefull with editing, keeping the same style, and use proper formatting and stuff. :)

**Comment by psy0rz** [comment]
oh i found this: https://nimblehq.co/blog/create-github-wiki-pull-request

but thats too much hassle for now :)

**Comment by danboid** [comment]
It wouldn't be a wiki any more if you moved it into the main repo but thats how other projects do it, just use markdown and link to it from the README. A wiki is less hassle and you're likely to get more contributions.

**Comment by danboid** [comment]
Done!

I've fixed a few typos and grammatical errors and added new "Running without root" and "Use alongside other snapshot tools" sections.

In the ssh section you say "Your user needs read/write access to /dev/zfs and you need to setup zfs permissions as well." I presume the user needing access to /dev/zfs is a FreeBSD only issue as I've never had to do anything with /dev/zfs under Linux to allow normal users to use ZFS?

**Comment by psy0rz** [comment]
Awesome thanks!

Usually those /dev permissions are ok. But not on all distros.

**Comment by psy0rz** [comment]
done, maybe you want to review it @danboid 

https://github.com/psy0rz/zfs_autobackup/wiki/Manual

**Comment by danboid** [comment]
> Awesome thanks!
> 
> Usually those /dev permissions are ok. But not on all distros.

I've never had to touch /dev/zfs ever under Ubuntu, Debian and Arch derivatives but I didn't know it was a thing until you mentioned it here. I'm pretty sure we don't need to cover it on the wiki.

**Comment by psy0rz** [comment]
I think the stuff about /dev/zfs can be moved to that new manual page. I already moved the run without root stuff there.

The getting started only should cover the basic usecase, with as little as extra (confusing) info as possible.

**Comment by danboid** [comment]
If I use `--no-snapshot.`, what does zfs-autobackup do?

**Comment by psy0rz** [comment]
Did you not read that manual i just posted??

**Comment by danboid** [comment]
Every line but this wasn't covered. I could try it out for myself to find out I suppose. I would presume its a no-op?

**Comment by mduller** [comment]
> If I use `--no-snapshot.`, what does zfs-autobackup do?

From https://github.com/psy0rz/zfs_autobackup/wiki/Manual#step-2-snapshotting
> Snapshotting can be skipped with `--no-snapshot`.

Yes, it will turn the snapshotting step into a no-op.

**Comment by psy0rz** [comment]
Yep it just doesnt create a new snapshot, but it still does everything else.

**Comment by psy0rz** [comment]
Oh sorry, i see now you where asking because youre actually trying to improve that manual page 😁

**Comment by danboid** [comment]
I was asking because I see zfs-autobackup as a ZFS snapshot tool so can it even do anything if it hasn't created any of its own snapshots? I presume it would do nothing if there were no existing snapshots and you ran without --no-snapshot right?

**Comment by psy0rz** [comment]
If you use it without target-path and with --no-snapshot, it still does the thinning.

But there are indeed valid combinations of parameters that result in not doing anything.
