### ISSUE TITLE
Preventing local snapshots

### ISSUE THREAD

**Issue by ozgurkazancci** [psy0rz/zfs_autobackup#238]
Hi.

Is it possible to NOT keep snapshots locally? Or automatically delete snapshots after they're posted to the remote server?

"--keep-source=0" did not help.

Full command that I use: 

_zfs-autobackup -v --clear-mountpoint --ssh-target mybackupsrv offsite1 zroot/backup --strip-path=1 --keep-source=0 --keep-target=3 --no-holds_

Thanks.

**Comment by psy0rz** [comment]
You always need atleast one snapshot (or bookmark but we dont suppoort that yet)

See https://github.com/psy0rz/zfs_autobackup/wiki/Common-snapshots-and-holds
