### ISSUE TITLE
Issues with Snapshot Format (Timestamp) and Thinning

### ISSUE THREAD

**Issue by norsemangrey** [psy0rz/zfs_autobackup#250]
I'm having an issue where old snapshots are not thinned when trying to resolve the snapshot format timestamp to a variable before passing it to the zfs-autobackup function.

I'm running multiple snapshot profiles in the same script and for the purpose of managing the snapshots later I would like them all to have the same timestamp in the snapshot name. Thus I'm trying to do something like in the below example, instead of passing timestamp format like this `SNAPSHOT_FORMAT="%Y-%m-%dT%H:%M:%S-auto"`. 

This works fine in that the snapshots are created and with the correct name, but thinning of old snapshots no longer works. Is this a bug, and if not is there another way to accomplish what I'm trying to do?

```
SOURCE_NAME=host-1
SNAPSHOT_FORMAT="$(date +%Y-%m-%dT%H:%M:%S)-auto"

zfs-autobackup SOURCE_NAME \
                    --keep-source=2 \
                    --property-format=snapshot-base:{} \
                    --snapshot-format $SNAPSHOT_FORMAT \
                    --exclude-received \
                    --progress \
                    --debug-output \
                    --verbose

zfs-autobackup SOURCE_NAME \
                    --keep-source=5,1d1w,1w1m \
                    --property-format=snapshot-pri-1:{} \
                    --snapshot-format $SNAPSHOT_FORMAT \
                    --exclude-received \
                    --progress \
                    --debug-output \
                    --verbose
```

**Comment by psy0rz** [comment]
look at the original snapshot format, there should be a {} in it, that gets filled in with the backup name automaticly.

**Comment by norsemangrey** [comment]
I'm probably being dense, but I'm not sure i follow .... 

The original snapshot format is this: `{}-%Y-%m-%dT%H:%M:%SZ` which means my snapshots would be named `host-1-<timestamp>`. I don't need the snapshot profile- / backup name as part of the snapshot name ... just the timestamp, but I need it to be the same for all profiles in the same script.

**Comment by norsemangrey** [comment]
Because I want to resolve the timestamp in the variable before passing it the zfs-autobackup function so that I get the the same timestamp for both snapshot profiles....otherwise there will be some seconds difference.

**Comment by psy0rz** [comment]
You're using a fixed string as snapshot "format". This makes it so that zfs-autobackup cant parse the dates and times of the existing snapshots.

If you just want the timestamp, use --snapshot-format=%Y-%m-%dT%H:%M:%SZ

Edwin
