### ISSUE TITLE
Possible problem in documentation (Running without root)

### ISSUE THREAD

**Issue by zlobniyshurik** [psy0rz/zfs_autobackup#266]
In full manual now:
---
On the receiving side, you need these:
```
root@target:~# zfs allow -u remoteuser compression,mountpoint,create,mount,receive,rollback,destroy,release,hold,userprop tank/backups/rpool
```
---
But with this settings my non-root user can not create new dataset

So I add `-d` switch to `zfs allow` string:
```
root@target:~# zfs allow -d -u remoteuser compression,mountpoint,create,mount,receive,rollback,destroy,release,hold,userprop tank/backups/rpool
```

And problem is gone.

P.S. FreeBSD on target side

**Comment by psy0rz** [comment]
its the same on bsd. strange, i think you had some other problem. 

if you have the problem again, please show the output , including --debug here so we can analyse.

**Comment by zlobniyshurik** [comment]
Sorry, I am not sure now that problem really was in -d switch.
At this moment all works perfectly.

P.S. Beside -d switch I added `canmount` and `nbmand` permissions for BSD-host. It was backup of some Samba folders.

**Comment by psy0rz** [comment]
no problem:)
