### ISSUE TITLE
Skip snapshot on non-zero return code of pre-command?

### ISSUE THREAD

**Issue by chrisb86** [psy0rz/zfs_autobackup#267]
Until now I was using the zfs-auto-snapshot script from zfsonlinux project. Over there the _--pre-snapshot_ option will skip the snapshot for this dataset, if the called command has a non-zero returnn code.

I use this fore frequent and hourly snpahots on my NAS to check if my spinning disk pool is sleeping and to prevent spinning up the disks. If they are sleeping, propably nothing has been changed since the last backup.

I discovered zfs_autobackup a few minutes ago and I couldn't find such a behaviour in the docs. WIll this work wit zfs_autosnapshot as well? It would love to use the same toolset on FreeBSD and Linux in the future.

**Comment by chrisb86** [comment]
Oh, I found it now. should work a needed.

**Comment by psy0rz** [comment]
Wouldn't it be better to create a script that checks if the harddisk is awake, and only then run zfs-autobackup in the first place?
