### ISSUE TITLE
pip install installs two versions

### ISSUE THREAD

**Issue by mariusvw** [psy0rz/zfs_autobackup#27]
Installed with:
```
pip --isolated install zfs-autobackup
```

When checking with ```pip list``` version **3.0rc4**  gets reported.

While typing the command I noticed that two versions existed, checking the diff between the two I notice that version 3.0-rc3 and 3.0-rc4 get installed with different names

```
# ls -al /usr/local/bin|grep zfs
-rwxr-xr-x    1 root  wheel    54698 Mar  8 20:14 zfs-autobackup
-rwxr-xr-x    1 root  wheel    53911 Mar  8 20:14 zfs_autobackup
```

**Comment by mariusvw** [comment]
As explained by @psy0rz this is on purpose due the transition from `zfs_autobackup` to `zfs-autobackup`

**Comment by psy0rz** [comment]
in the next release the underscore version will be removed.
