### ISSUE TITLE
Show holds of incompatible snapshots when testing

### ISSUE THREAD

**Issue by pol66** [psy0rz/zfs_autobackup#276]
Testing what will happen is very practical thing. 
But sometimes the report given by --dry-run does not completely show 
a possible problem when running without --dry-run.

E.g. you can use --destroy-incompatible and it does not show any problem
during --dry-run but it complains without it because of possible "holds" 
on the incompatible snapshot.

So it would be practical to test if the incompatible snapshots have some holds
and report such a dataset as "failed".

**Comment by psy0rz** [comment]
yes, the test run can only do so much. Its merely to see what is selected, what will be transferred, and of things like common snapshots are ok, assuming all external operation succeed.

we cant extend it with every possible external issue that can go wrong. (next would be an available disk space check etc etc)
