### ISSUE TITLE
Customize ZFS_MAX_UNCHANGED_BYTES

### ISSUE THREAD

**Issue by amahoneyLIT** [psy0rz/zfs_autobackup#33]
Currently `ZFS_MAX_UNCHANGED_BYTES=200000`, but in my testing before implementing zfs_autobackup, I find it is not detecting my changes unless I make them really big.

e.g. writing some random text to a file:
> sudo zfs get -H -ovalue -p written@test-20200310202035 mypool/test
77824

200k seems arbitrary - expose as an argument?

**Comment by psy0rz** [comment]
Compression might affect the amount of bytes written to a pool.

The number is quite arbitrary indeed, i agree it should be exposed as an argument and better documented. (--allow-empty is related to this)

**Comment by amahoneyLIT** [comment]
It is tricky... I wonder if there is a better method than checking written bytes. Sometimes you could write no changes to files but change a dataset property and want that to be replicated.

**Comment by psy0rz** [comment]
Then the best option is to use --allow-empty, so it will always make snapshots of all the selected datasets.

**Comment by psy0rz** [comment]
I also will add a --minimum-changed parameter. --allow-empty will then be the same as --minimum-changed=0

default for --minimum-changed will probably that 200000

**Comment by psy0rz** [comment]
fixed in 3.0rc7 https://pypi.org/project/zfs-autobackup/3.0rc7/

its called the --min-change parameter and the default is 200000.
