### ISSUE TITLE
local snapshots gone before attempting to replicate with --other-snapshots

### ISSUE THREAD

**Issue by amahoneyLIT** [psy0rz/zfs_autobackup#35]
I have zfs-auto-snapshot running to handle local frequent/hourly/daily/monthly snapshots. I ran my zfs-autobackup script with your new --other-snapshots flag so that all the zfs-auto-snap snapshots get replicated. However, I ran into an issue where one of my hourly snapshots expired and was deleted in between calling zfs-autobackup and it reaching that particular incremental send, resulting in 

! [Target] STDERR|> cannot send mypool/dataset@zfs-auto-snap_hourly-2020-03-12-16h00U: snapshot mypool/dataset@zfs-auto-snap_hourly-2020-03-12-16h00U does not exist

...

and then failing to send the rest of the snapshots for that dataset.

I suppose I could stop the zfs-auto-snapshot service before doing backups, but that could leave the system vulnerable for hours depending how long the replication takes. 

Any ideas on what good practice would be? Is it feasible for zfs-autobackup to "refresh" the snpashot list as it goes?

**Comment by gdevenyi** [comment]
I believe this is what bookmarks are for:
https://utcc.utoronto.ca/~cks/space/blog/solaris/ZFSBookmarksWhatFor

**Comment by amahoneyLIT** [comment]
To better phrase the problem

When initially calling zfs-autobackup, say the following snapshots exist

mypool/mydataset@zfs-auto-snap_frequent-2020-03-13-16h00U
mypool/mydataset@zfs-auto-snap_frequent-2020-03-13-16h15U
mypool/mydataset@zfs-auto-snap_frequent-2020-03-13-16h30U
mypool/mydataset@zfs-auto-snap_frequent-2020-03-13-16h45U

zfs-autobackup does it's job sending the a bunch of datasets, and then it's time to send mypool/mydataset. But the clock happened to tick past 17h00 while the other datasets were replicating, resulting in local snapshots

~~mypool/mydataset@zfs-auto-snap_frequent-2020-03-13-16h00U~~ destroyed
mypool/mydataset@zfs-auto-snap_frequent-2020-03-13-16h15U
mypool/mydataset@zfs-auto-snap_frequent-2020-03-13-16h30U
mypool/mydataset@zfs-auto-snap_frequent-2020-03-13-16h45U
mypool/mydataset@zfs-auto-snap_frequent-2020-03-13-17h00U

so we dont have a 16h00U snapshot, nor do we want to replicate it. We would like to replicate 16h15 through 17h00, but zfs-autobackup will throw an exception and not send any because the 16h00 snapshot no longer exists.

workaround is to `systemctl stop zfs-snapshot-frequent.timer` before zfs-autobackup, and `systemctl start zfs-snapshot-frequent.timer` after

Not sure I understand how bookmarks would solve this; let me know if I'm missing something, or I just didn't explain it enough before

**Comment by psy0rz** [comment]
Ah thats very interesting. I wil have to think about it. Perhaps a --refresh or --no-caching flag would be ice for that.

Or is an --ignore-missing flag good enough for you? (although it might miss some in-between snapshots perhaps)

**Comment by amahoneyLIT** [comment]
Ignoring missing could be simpler than refreshing, and seems like a safe thing to do at first thought

**Comment by psy0rz** [comment]
Another question: how do you destroy the snapshots on your backup? Currently zfs-autobackup only destroys snapshots it has created itself. I pondering to change this so it uses the creation-time of a snapshot, instead of getting the time from the snapshot-name. This way i could also thin-out other snapshots.

**Comment by amahoneyLIT** [comment]
I currently don't, but I was thinking I could make a simple script to list all the snapshots on the source, and `zfs destroy` all snapshots on the target not in the list.

**Comment by psy0rz** [comment]
Perhaps a better way would be a option that holds ALL snaphots in a dataset so that they cant be destroyed during transfer. 

If you make sure your cleanup script use zfs destroy -d, it wont give errors and it will still destroy the snapshots after zfs-autobackup releases them.

Would that be a good solution? (via an option called something like --hold-all)

**Comment by psy0rz** [comment]
Someone still wants this option?
