### ISSUE TITLE
support for pre- and post-snapshot scripts

### ISSUE THREAD

**Issue by dkew8** [psy0rz/zfs_autobackup#39]
Currently, the script only performs the ZFS related operations on the target system. Therefore, all the supporting actions like stopping and restarting the service must be done outside of it. This can lead to prolonged downtime. As the snapshot itself is almost immediate, it would make sense to move the actions to the point between snapshots and the actual transfer of the data. At this time, we're using --no-send/--no-snapshot combination, which is fine, but the support for adding the scripts would be much more convenient.

**Comment by psy0rz** [comment]
This should be fairely easy to implement.

**Comment by psy0rz** [comment]
fixed thanks to @tuffnatty
