### ISSUE TITLE
Options missing in FreeBSD (xigmanas)

### ISSUE THREAD

**Issue by coraxosm** [psy0rz/zfs_autobackup#52]
Options 

 --clear-mountpoint
 --clear-refreservation

does not work cause of different "zfs receive -o" behavior.

FreeBSD 12.1-RELEASE-p7

**Comment by psy0rz** [comment]
Can someone with access to this version figure out if there is another way to implement these 2 options? Its probably an older version the zfs userspace utils.

**Comment by coraxosm** [comment]
Well, solution to disable automount is 'zfs set canmount=noauto dataset' afterwards, no ideas considering second option. =) BR Oleg.  26.08.2020, 14:51, "DatuX" <notifications@github.com>: Can someone with access to this version figure out if there is another way to implement these 2 options? Its probably an older version the zfs userspace utils.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by coraxosm** [comment]
[coraxosm@nas ~]$ zfs receivemissing snapshot argumentusage:        receive|recv [-vnsFu] <filesystem|volume|snapshot>        receive|recv [-vnsFu] [-o origin=<snapshot>] [-d | -e] <filesystem>        receive|recv -A <filesystem|volume> For the property list, run: zfs set|get For the delegated permission list, run: zfs allow|unallow 26.08.2020, 14:51, "DatuX" <notifications@github.com>: Can someone with access to this version figure out if there is another way to implement these 2 options? Its probably an older version the zfs userspace utils.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mariusvw** [comment]
The solution is indeed an older version of ZFS.
On ZFSforLinux they implemented this already, due migration FreeBSD is a bit behind on this.

Like @coraxosm suggested, a solution is indeed to set it afterwards.

```
# [Target] zroot/ROOT/default@duvel_zroot-20201102220054: Enabled resume support
# [Target] RUN    >  zfs recv -u -o canmount=noauto -v -s zroot/backup/ROOT/default
# [Target] Piping input
! [Target] STDERR > invalid optionusage:
# [Target] STDERR >     receive|recv [-vnsFu] <filesystem|volume|snapshot>
# [Target] STDERR >     receive|recv [-vnsFu] [-o origin=<snapshot>] [-d | -e] <filesystem>
# [Target] STDERR >     receive|recv -A <filesystem|volume>
! [Target] STDERR > 
! [Target] STDERR > For the property list, run: zfs set|get
! [Target] STDERR > 
! [Target] STDERR > For the delegated permission list, run: zfs allow|unallow
# [Target] STDERR|> skipping snapshot zroot/ROOT/default@duvel_zroot-20201102220823 because it was created after the destination snapshot (duvel_zroot-20201102220054)
# [Target] STDERR|> skipping snapshot zroot/ROOT/default@duvel_zroot-20201102221356 because it was created after the destination snapshot (duvel_zroot-20201102220054)
# [Target] STDERR|> skipping snapshot zroot/ROOT/default@duvel_zroot-20201102222617 because it was created after the destination snapshot (duvel_zroot-20201102220054)
# [Target] EXIT   > 2
# [Target] EXIT  |> 141
! [Source] zroot/ROOT/default: FAILED: Command '(pipe)' returned non-zero exit status 141.
! Exception: Command '(pipe)' returned non-zero exit status 141.
```
