### ISSUE TITLE
No way to turn off thinning

### ISSUE THREAD

**Issue by fhriley** [psy0rz/zfs_autobackup#54]
Destroying snapshots can be I/O intensive. Because of that it is preferable to schedule thinning when the pool is not busy. This is not possible with `zfs-autobackup` because it does not provide an option to turn off thinning.

**Comment by psy0rz** [comment]
Good point, i think i just forgot to add it. I'll create a --no-thinning option.

Edwin

**Comment by psy0rz** [comment]
Added this option. Please thumbs up if you are waiting for this option to be available via pip.

**Comment by psy0rz** [comment]
Done, use:

pip install --upgrade --pre zfs-autobackup

**Comment by 0x0a11c0de** [comment]
Thanks!

**Comment by ierdnah** [comment]
Please add this flag in the "Usage" section on https://github.com/psy0rz/zfs_autobackup

**Comment by psy0rz** [comment]
its still the usage for 3.0. i was planning to update it once 3.1 is stable. :)

**Comment by psy0rz** [comment]
updated it anyway :)
