### ISSUE TITLE
zfs recv error?

### ISSUE THREAD

**Issue by nktech1135** [psy0rz/zfs_autobackup#55]
I'm trying to figure out where to go from here. I get the following on completion of backing up a zfs dataset.
root@freenas[~]# zfs-autobackup --ssh-source 10.33.55.70 mail data1/mail --progress --verbose
  zfs-autobackup v3.0 - Copyright 2020 E.H.Eefting (edwin@datux.nl)

  #### Source settings
  [Source] Datasets on: 10.33.55.70
  [Source] Keep the last 10 snapshots.
  [Source] Keep every 1 day, delete after 1 week.
  [Source] Keep every 1 week, delete after 1 month.
  [Source] Keep every 1 month, delete after 1 year.
  [Source] Selects all datasets that have property 'autobackup:mail=true' (or childs of datasets that have 'autobackup:mail=child')

  #### Selecting
  [Source] mail/subvol-104-disk-0: Selected (direct selection)

  #### Snapshotting
  [Source] Creating snapshots mail-20200928105136 in pool mail

  #### Target settings
  [Target] Datasets are local
  [Target] Keep the last 10 snapshots.
  [Target] Keep every 1 day, delete after 1 week.
  [Target] Keep every 1 week, delete after 1 month.
  [Target] Keep every 1 month, delete after 1 year.
  [Target] Receive datasets under: data1/mail

  #### Sending and thinning
  [Source] mail/subvol-104-disk-0@mail-20200925045627: Destroying
  [Target] data1/mail/mail/subvol-104-disk-0@mail-20200925045627: Destroying
  [Target] data1/mail/mail/subvol-104-disk-0@mail-20200928105136: receiving incremental
! [Target] STDERR > internal error: Invalid argument
! [Source] mail/subvol-104-disk-0: FAILED: Command '[b'zfs', b'recv', b'-u', b'-v', b'-s', b'data1/mail/mail/subvol-104-disk-0']' died with <Signals.SIGABRT: 6>.
! 1 failures!

Thoughts?

**Comment by psy0rz** [comment]
A SIGABRT sounds pretty bad, altough strange errors do occur from linux to freenas.

Run it with --debug and try to run the command manually to see what happens.

Check the dmesg for any kernel errors during backup.

Try running it with --ignore-transfer-error. This will ignore the error but still verify if the snapshot has been transferred. (i sometimes use this when i backup between different operating systems)

Edwin

**Comment by nktech1135** [comment]
--ignore-transfer-errors does let it go through. I'm not sure what the issue is as it doesn't occur on some systems and it does on others. I'll just close this for now and if i run into something more definite i'll post that.

Thanks for the help.
