### ISSUE TITLE
Send or Recv Error?

### ISSUE THREAD

**Issue by jemail99** [psy0rz/zfs_autobackup#56]
I am trying to get zfs-autoback on FreeBSD 12.1 to create snapshots of zroot and send them to a zfs pool on raidz hdd on the same server. I get the following errors on the send portion of the zfs-autobackup command. I have no idea what this error means or how to resolve it.
Any help would be appreciated.

`# zfs-autobackup --test --verbose --progress hddstorage /storage/Recovery/STEEL/snapshots/`
  zfs-autobackup v3.0 - Copyright 2020 E.H.Eefting (edwin@datux.nl)
  TEST MODE - SIMULATING WITHOUT MAKING ANY CHANGES

  #### Source settings
  [Source] Datasets are local
  [Source] Keep the last 10 snapshots.
  [Source] Keep every 1 day, delete after 1 week.
  [Source] Keep every 1 week, delete after 1 month.
  [Source] Keep every 1 month, delete after 1 year.
  [Source] Selects all datasets that have property 'autobackup:hddstorage=true' (or childs of datasets that have 'autobackup:hddstorage=child')

  #### Selecting
  [Source] zroot: Selected (direct selection)
  [Source] zroot/ROOT: Selected (inherited selection)
  [Source] zroot/ROOT/12.1-RELEASE: Selected (inherited selection)
  [Source] zroot/ROOT/12.1-RELEASE-p10: Selected (inherited selection)
  [Source] zroot/ROOT/current: Selected (inherited selection)
  [Source] zroot/ROOT/default: Selected (inherited selection)
  [Source] zroot/swap: Ignored (disabled)
  [Source] zroot/tmp: Ignored (disabled)
  [Source] zroot/usr: Selected (inherited selection)
  [Source] zroot/usr/home: Selected (inherited selection)
  [Source] zroot/usr/ports: Selected (inherited selection)
  [Source] zroot/usr/src: Selected (inherited selection)
  [Source] zroot/var: Selected (inherited selection)
  [Source] zroot/var/audit: Selected (inherited selection)
  [Source] zroot/var/crash: Selected (inherited selection)
  [Source] zroot/var/log: Selected (inherited selection)
  [Source] zroot/var/mail: Selected (inherited selection)
  [Source] zroot/var/tmp: Ignored (disabled)

  #### Snapshotting
  [Source] Creating snapshots hddstorage-20201018113559 in pool zroot

  #### Target settings
  [Target] Datasets are local
  [Target] Keep the last 10 snapshots.
  [Target] Keep every 1 day, delete after 1 week.
  [Target] Keep every 1 week, delete after 1 month.
  [Target] Keep every 1 month, delete after 1 year.
  [Target] Receive datasets under: /storage/Recovery/STEEL/snapshots/

  #### Sending and thinning
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/ROOT: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/ROOT/12.1-RELEASE: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/ROOT/12.1-RELEASE-p10: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/ROOT/current: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/ROOT/default: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/usr: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/usr/home: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/usr/ports: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/usr/src: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/var: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/var/audit: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/var/crash: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/var/log: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot/var/mail: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! 15 failures!

  TEST MODE - DID NOT MAKE ANY CHANGES!

When I run with --debug I get the following:

`# zfs-autobackup --debug --test --verbose --progress hddstorage /storage/Recovery/STEEL/snapshots`
  zfs-autobackup v3.0 - Copyright 2020 E.H.Eefting (edwin@datux.nl)

  TEST MODE - SIMULATING WITHOUT MAKING ANY CHANGES

  #### Source settings
  [Source] Datasets are local
  [Source] Keep the last 10 snapshots.
  [Source] Keep every 1 day, delete after 1 week.
  [Source] Keep every 1 week, delete after 1 month.
  [Source] Keep every 1 month, delete after 1 year.
  [Source] Selects all datasets that have property 'autobackup:hddstorage=true' (or childs of datasets that have 'autobackup:hddstorage=child')

  #### Selecting
  [Source] Getting selected datasets
  [Source] RUN    >  zfs get -t volume,filesystem -o name,value,source -s local,inherited -H autobackup:hddstorage
  [Source] zroot: Selected (direct selection)
  [Source] zroot/ROOT: Selected (inherited selection)
  [Source] zroot/ROOT/12.1-RELEASE: Selected (inherited selection)
  [Source] zroot/ROOT/12.1-RELEASE-p10: Selected (inherited selection)
  [Source] zroot/ROOT/current: Selected (inherited selection)
  [Source] zroot/ROOT/default: Selected (inherited selection)
  [Source] zroot/swap: Ignored (disabled)
  [Source] zroot/tmp: Ignored (disabled)
  [Source] zroot/usr: Selected (inherited selection)
  [Source] zroot/usr/home: Selected (inherited selection)
  [Source] zroot/usr/ports: Selected (inherited selection)
  [Source] zroot/usr/src: Selected (inherited selection)
  [Source] zroot/var: Selected (inherited selection)
  [Source] zroot/var/audit: Selected (inherited selection)
  [Source] zroot/var/crash: Selected (inherited selection)
  [Source] zroot/var/log: Selected (inherited selection)
  [Source] zroot/var/mail: Selected (inherited selection)
  [Source] zroot/var/tmp: Ignored (disabled)

  #### Snapshotting
  [Source] zroot: Getting snapshots
  [Source] zroot: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot
  [Source] zroot/ROOT: Getting snapshots
  [Source] zroot/ROOT: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/ROOT
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/ROOT
  [Source] zroot/ROOT/12.1-RELEASE: Getting snapshots
  [Source] zroot/ROOT/12.1-RELEASE: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/ROOT/12.1-RELEASE
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/ROOT/12.1-RELEASE
  [Source] zroot/ROOT/12.1-RELEASE-p10: Getting snapshots
  [Source] zroot/ROOT/12.1-RELEASE-p10: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/ROOT/12.1-RELEASE-p10
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/ROOT/12.1-RELEASE-p10
  [Source] zroot/ROOT/current: Getting snapshots
  [Source] zroot/ROOT/current: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/ROOT/current
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/ROOT/current
  [Source] zroot/ROOT/default: Getting snapshots
  [Source] zroot/ROOT/default: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/ROOT/default
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/ROOT/default
  [Source] zroot/usr: Getting snapshots
  [Source] zroot/usr: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/usr
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/usr
  [Source] zroot/usr/home: Getting snapshots
  [Source] zroot/usr/home: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/usr/home
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/usr/home
  [Source] zroot/usr/ports: Getting snapshots
  [Source] zroot/usr/ports: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/usr/ports
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/usr/ports
  [Source] zroot/usr/src: Getting snapshots
  [Source] zroot/usr/src: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/usr/src
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/usr/src
  [Source] zroot/var: Getting snapshots
  [Source] zroot/var: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/var
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/var
  [Source] zroot/var/audit: Getting snapshots
  [Source] zroot/var/audit: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/var/audit
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/var/audit
  [Source] zroot/var/crash: Getting snapshots
  [Source] zroot/var/crash: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/var/crash
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/var/crash
  [Source] zroot/var/log: Getting snapshots
  [Source] zroot/var/log: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/var/log
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/var/log
  [Source] zroot/var/mail: Getting snapshots
  [Source] zroot/var/mail: Checking if filesystem exists
  [Source] RUN    >  zfs list zroot/var/mail
  [Source] RUN    >  zfs list -d 1 -r -t snapshot -H -o name zroot/var/mail
  [Source] Creating snapshots hddstorage-20201018115848 in pool zroot
  [Source] SKIP   >  zfs snapshot zroot@hddstorage-20201018115848 zroot/ROOT@hddstorage-20201018115848 zroot/ROOT/12.1-RELEASE@hddstorage-20201018115848 zroot/ROOT/12.1-RELEASE-p10@hddstorage-20201018115848 zroot/ROOT/current@hddstorage-20201018115848 zroot/ROOT/default@hddstorage-20201018115848 zroot/usr@hddstorage-20201018115848 zroot/usr/home@hddstorage-20201018115848 zroot/usr/ports@hddstorage-20201018115848 zroot/usr/src@hddstorage-20201018115848 zroot/var@hddstorage-20201018115848 zroot/var/audit@hddstorage-20201018115848 zroot/var/crash@hddstorage-20201018115848 zroot/var/log@hddstorage-20201018115848 zroot/var/mail@hddstorage-20201018115848

  #### Target settings
  [Target] Datasets are local
  [Target] Keep the last 10 snapshots.
  [Target] Keep every 1 day, delete after 1 week.
  [Target] Keep every 1 week, delete after 1 month.
  [Target] Keep every 1 month, delete after 1 year.
  [Target] Receive datasets under: /storage/Recovery/STEEL/snapshots

  #### Sending and thinning
  [Target] /storage/Recovery/STEEL/snapshots: Checking if filesystem exists
  [Target] RUN    >  zfs list /storage/Recovery/STEEL/snapshots
  [Target] /storage/Recovery/STEEL/snapshots: Checking if filesystem exists
  [Target] RUN    >  zfs list /storage/Recovery/STEEL/snapshots
  [Source] zpool zroot: Getting zpool properties
  [Source] RUN    >  zpool get -H -p all zroot
  [Target] zpool : Getting zpool properties
  [Target] RUN    >  zpool get -H -p all
! [Target] STDERR > cannot open '': name must begin with a letter
! [Source] zroot: FAILED: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
! Exception: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/bin/zfs-autobackup", line 1862, in <module>
    sys.exit(zfs_autobackup.run())
  File "/usr/local/bin/zfs-autobackup", line 1825, in run
    fail_count=self.sync_datasets(source_node, source_datasets)
  File "/usr/local/bin/zfs-autobackup", line 1703, in sync_datasets
    target_features=target_node.get_zfs_pool(target_dataset.split_path()[0]).features
  File "/usr/local/bin/zfs-autobackup", line 521, in features
    for (key,value) in self.properties.items():
  File "/usr/local/bin/zfs-autobackup", line 252, in __get__
    obj._cached_properties[propname]=self.func(obj)
  File "/usr/local/bin/zfs-autobackup", line 510, in properties
    for pair in self.zfs_node.run(tab_split=True, cmd=cmd, readonly=True, valid_exitcodes=[ 0 ]):
  File "/usr/local/bin/zfs-autobackup", line 456, in run
    raise(subprocess.CalledProcessError(p.returncode, encoded_cmd))
subprocess.CalledProcessError: Command '[b'zpool', b'get', b'-H', b'-p', b'all', b'']' returned non-zero exit status 1.

**Comment by jemail99** [comment]
It seems this error is caused by the leading / in the path /storage/Recovery/STEEL/snapshots?
Is this intentional or by design?
I'm used to specifying absolute paths but maybe this is not how zfs expects paths? I'm new to zfs and it's usage.

**Comment by psy0rz** [comment]
Correct, this is the way ZFS works: A name of a dataset never starts with a /

It might be confusing because the mount point DOES start with a / and is usually (but not always) the same as the dataset name.

However i will make a change so zfs-autobackup treats this as an error, so its more clear what is happening. 

Thanks.
