### ISSUE TITLE
zfs rollback dataset busy issue

### ISSUE THREAD

**Issue by jemail99** [psy0rz/zfs_autobackup#58]
Hi,

I cannot rollback snapshots as the latest snapshot created with zfs-autobackup is always busy and cannot be destroyed!

`zfs rollback -r zroot/var/mail@hddstorage-20201027135626`
cannot destroy 'zroot/var/mail@hddstorage-20201027172933': dataset is busy

This goes for all snapshots created for the other zroot sub-folders I have 'tagged' with the hddstorage property.

Is this a zfs feature again? I use bectl to take boot environment snapshots, is zfs-autobackup incompatible with bectl and boot environments? It seems very counter intuitive that I cannot rollback before the last snapshot. What could be causing dataset busy when the latest dataset is attempting to be being destroyed by zfs?

**Comment by jemail99** [comment]
I have discovered that my latest snapshots are tagged with `zfs_autobackup:hhdstorage`.
This prevents rollback to a previous snapshot using `zfs rollback` command as zfs_autobackup has in effect put a hold on the latest snapshot. Using `zfs release` will allow the latest snapshot to be deleted when rolling back to previous snapshots.

Why does zfs_autobackup tag the latest snapshot with `zfs_autobackup:hhdstorage`?
Should I be using the `--rollback` option instead? The explanation for  `--rollback` is not clear to me, but as I said I'm new to zfs so maybe that is why I don't understand.

**Comment by jemail99** [comment]
Using the --no-holds option prevents the dataset busy problem on FreeBSD 12.2.
Please mark this issue solved.

**Comment by psy0rz** [comment]
Sorry for the late reply: This is indeed a feature, to prevent accidental deletion of the common snapshot.

--no-holds disables this.

Keep in mind that if you delete the common snapshot, you cant continue the backup. Either you have to use --destroy-incompatible or delete all backups on the target and start over.
