### ISSUE TITLE
Invalid option x on FreeBSD 12.2

### ISSUE THREAD

**Issue by jemail99** [psy0rz/zfs_autobackup#59]
Freebsd 12.2
zfs-autoback 3.0

`/usr/local/bin/zfs-autobackup --other-snapshots --no-holds --clear-refreservation --clear-mountpoint hddstorage storage/Recovery/STEEL/snapshots`

! [Target] STDERR > invalid option 'x'
! [Target] STDERR > usage:
! [Target] STDERR >
! [Target] STDERR > For the property list, run: zfs set|get
! [Target] STDERR >
! [Target] STDERR > For the delegated permission list, run: zfs allow|unallow
! [Source] zroot: FAILED: Command '[b'zfs', b'recv', b'-u', b'-x', b'refreservation', b'-o', b'canmount=noauto', b'-v', b'-s', b'storage/Recovery/STEEL/snapshots/zroot']' returned non-zero exit status 2.
! [Target] STDERR > invalid option 'x'
! [Target] STDERR > usage:
! [Target] STDERR >
! [Target] STDERR > For the property list, run: zfs set|get
! [Target] STDERR >
! [Target] STDERR > For the delegated permission list, run: zfs allow|unallow
! [Source] zroot/ROOT: FAILED: Command '(pipe)' died with <Signals.SIGPIPE: 13>.
...
! 12 failures!

**Using --debug:**
[Target] STDERR|> full        zroot@hddstorage-20201104202122 12912
[Target] STDERR|> size        12912
[Target] STDERR|> full        zroot@hddstorage-20201104202122 12912
! [Target] STDERR > invalid option 'x'
! [Target] STDERR > usage:
[Target] STDERR >     receive|recv [-vnsFu] <filesystem|volume|snapshot>
[Target] STDERR >     receive|recv [-vnsFu] [-o origin=<snapshot>] [-d | -e] <filesystem>
[Target] STDERR >     receive|recv -A <filesystem|volume>
! [Target] STDERR >
! [Target] STDERR > For the property list, run: zfs set|get
! [Target] STDERR >
! [Target] STDERR > For the delegated permission list, run: zfs allow|unallow
! [Source] zroot: FAILED: Command '[b'zfs', b'recv', b'-u', b'-x', b'refreservation', b'-o', b'canmount=noauto', b'-v', b'-s', b'storage/Recovery/STEEL/snapshots/zroot']' returned non-zero exit status 2.
! Exception: Command '[b'zfs', b'recv', b'-u', b'-x', b'refreservation', b'-o', b'canmount=noauto', b'-v', b'-s', b'storage/Recovery/STEEL/snapshots/zroot']' returned non-zero exit status 2.
Traceback (most recent call last):
  File "/usr/local/bin/zfs-autobackup", line 1862, in <module>
    sys.exit(zfs_autobackup.run())
  File "/usr/local/bin/zfs-autobackup", line 1825, in run
    fail_count=self.sync_datasets(source_node, source_datasets)
  File "/usr/local/bin/zfs-autobackup", line 1707, in sync_datasets
    source_dataset.sync_snapshots(target_dataset, show_progress=self.args.progress, features=common_features, filter_properties=filter_properties, set_properties=set_properties, ignore_recv_exit_code=self.args.ignore_transfer_errors, source_holds= not self.args.no_holds, rollback=self.args.rollback, raw=self.args.raw, other_snapshots=self.args.other_snapshots, no_send=self.args.no_send, destroy_incompatible=self.args.destroy_incompatible)
  File "/usr/local/bin/zfs-autobackup", line 1295, in sync_snapshots
    source_snapshot.transfer_snapshot(target_snapshot, features=features, prev_snapshot=prev_source_snapshot, show_progress=show_progress,   filter_properties=allowed_filter_properties, set_properties=allowed_set_properties, ignore_recv_exit_code=ignore_recv_exit_code, resume_token=resume_token, raw=raw)
  File "/usr/local/bin/zfs-autobackup", line 1060, in transfer_snapshot
    target_snapshot.recv_pipe(pipe, features=features, filter_properties=filter_properties, set_properties=set_properties, ignore_exit_code=ignore_recv_exit_code)
  File "/usr/local/bin/zfs-autobackup", line 1022, in recv_pipe
    self.zfs_node.run(cmd, input=pipe, valid_exitcodes=valid_exitcodes)
  File "/usr/local/bin/zfs-autobackup", line 456, in run
    raise(subprocess.CalledProcessError(p.returncode, encoded_cmd))
subprocess.CalledProcessError: Command '[b'zfs', b'recv', b'-u', b'-x', b'refreservation', b'-o', b'canmount=noauto', b'-v', b'-s', b'storage/Recovery/STEEL/snapshots/zroot']' returned non-zero exit status 2.

**From the man page in Freebsd**:
     zfs receive|recv [-vnsFu] [-o origin=snapshot] filesystem|volume|snapshot
     zfs receive|recv [-vnsFu] [-d | -e] [-o origin=snapshot] filesystem

There does not seem to be an option x.
Any ideas what is causing this?

**Comment by psy0rz** [comment]
See #52 . FreeBSD doesnt support this (yet).

For now you need to clear these things manually after a backup.
