### ISSUE TITLE
Enabling -D for sending a deduped stream don't work

### ISSUE THREAD

**Issue by knuuuut** [psy0rz/zfs_autobackup#64]
Hello,
I want to replicate heavily deduped datasets and I was missing the -D option while sending.
After looking at the code I've found an outcommented section about this.
Just removing the the "#" in that code section results in a lot of error output.

`        #NOTE: performance is usually worse with this option, according to manual`
`        #also -D will be depricated in newer ZFS versions`
`        if not resume:`
`        if "-D" in self.zfs_node.supported_send_options:`
`            cmd.append("-D") # dedupped stream, sends less duplicate data`

Additionaly I use the option "dedup=skein" instead of  "dedup=on" for performance reasons (much better!) and this may be the reason why this won't work.
Anyway, I don't know much about python and any help would be nice.

**Comment by psy0rz** [comment]
As you can see you shouldn't use the -D option anymore since it will be depricated.

Also the -D has nothing to do with the dedup option, it will just try to dedup the stream a little bit, without using actual dedup info thats on disk.

I'm forgot all the details, but -D shouldn't be used anymore.
