### ISSUE TITLE
Thin source trigger

### ISSUE THREAD

**Issue by kahvis** [psy0rz/zfs_autobackup#66]
Great job!

Do you have any interest to implement next:

You have several thin source zfs systems with a user data on them. You divide systems to datasets by a user. User login / modify data rarely on all systems. So what if there is some trigger system to start back upping. Maybe the backup server should look up new snapshots on thin sources and if it appearing then take a backup from it. That is leading to situation that backup times follows logout times. Maybe even have a schedule to feed "unused" systems to keep up to date.

You can probably guess the use case. Linux home folders sync between multiple computers.

**Comment by psy0rz** [comment]
I think zfs-autobackup already sort of does this: If a dataset has no changes since the last backup, it will ignore it.

You can use --min-change to specify how many bytes should be changed before making a backup.

That way you can let the zfs-autobackup run in a cronjob every hour or so, and it will make only backups if something has changed.

**Comment by kahvis** [comment]
Thank you from response!

How about feeding out of date computers when they come online or when user try to log in?

**Comment by psy0rz** [comment]
As soon as they are a while online, the cronjob should connect and start/continue the backup, right?

**Comment by kahvis** [comment]
I mean this:
Working computer 1 > log out > backup to server > server push changes to computer 2,3,4,5
If you log in again on any Computer 2,3,4,5 you have state of when you have logged out on computer 1.

**Comment by psy0rz** [comment]
Ah right. 

Wouldn't it be easier to just have a central fileserver that all the workstations use?

**Comment by kahvis** [comment]
Yes, of course. I thought that ZFS have advantages:

- Network issues ( always local copys )
- You can sync also over internet, sync has done before people can change location to other "office"
- backup laptop when it arrived local wifi and feeding desktops
- most IMPORTANT encryption

**Comment by psy0rz** [comment]
Well that sounds like a whole project that zfs-autobackup could be part of. :)

Tell me what kind of features you exactly need and we can talk about it.
