### ISSUE TITLE
cannot receive incremental stream: destination has been modified since most recent snapshot

### ISSUE THREAD

**Issue by GaetanLepage** [psy0rz/zfs_autobackup#67]
Hello !
Thank you for developing this great piece of software !

I have set up a simple back up workflow which was working great until now.
On my latest try to perform my backup, I got the following error:
`cannot receive incremental stream: destination backup/zfspool has been modified since most recent snapshot`
on the target side.

How could I solve this problem ?

Thank you very much in advance !

**Comment by psy0rz** [comment]
there was probably something thats changed. use the --rollback option. :)

**Comment by GaetanLepage** [comment]
Indeed it works !
Thank you very much !

**Comment by psy0rz** [comment]
No problem, i will update the documentation on the front page :)

**Comment by psy0rz** [comment]
https://github.com/psy0rz/zfs_autobackup#it-says-cannot-receive-incremental-stream-destination-has-been-modified-since-most-recent-snapshot

**Comment by psy0rz** [comment]
see https://github.com/psy0rz/zfs_autobackup/wiki/Mounting
