### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by psy0rz** [psy0rz/zfs_autobackup#68]
The current date/time format is pretty unreadable.

Change it to:

pool/dataset@snapname_2021-02-10_12:49.00

**Comment by mariusvw** [comment]
Personally I don't have issues with using a simple unix timestamp.
Maybe use a more precise time so you can make multiple backups in the same second without overlap.

```
zfs list -t snapshot -o name,creation
```

When dumping a backup to a file and use it on other filesystems I don't think it is handy to have colons in the filename.
For example, macOS rewrites these to slashes.

**Comment by psy0rz** [comment]
Well its not set in stone. I dont want to use characters that need escaping. :) Offcourse it will stay backwards compatible with the old existing snapshots.

If everybody just loves the current format, I wont change it. :)

**Comment by tpyro** [comment]
If you are going to change the format, I would recommend looking at [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations) where the letter 'T' is specified as the separator. ZnapZend uses 2021-01-12T14:00:00, but 20210112T140000 is also allowed if you don't want colons.

**Comment by psy0rz** [comment]
I like ZnapZend's format. Is it still iso 8601 compatible?

**Comment by tpyro** [comment]
Yes. I believe both examples above are compatible. It doesn't help with mariusvw's concerns above. Does the programming even depend on the snapshot name? Perhaps it could be "%Y-%m-%dT%H:%M:%S" by default but customizable?

Personally, coming from ZnapZend myself, I'm a bit thrown by having the backup job name as part of the snapshot. But it seems the programming might require that.

**Comment by psy0rz** [comment]
@tpyro the backup name in the snapshot has two reasons:

- Make it clearer for the admin where a snapshot belongs to.
- Make it possible to replicate data to multiple locations. This way the snapshots on the source do not conflict with each-other.

**Comment by psy0rz** [comment]
I just added the --snapshot-format option to fix #87 . So that essentially fixes this as well.  The default format stayed the same offcourse to keep it compatible.
