### ISSUE TITLE
Question: Backup of pool and/or dataset

### ISSUE THREAD

**Issue by fphsFischmeister** [psy0rz/zfs_autobackup#69]
Hi, 

I am pretty new to zfs, pool, datasets and snapshots. I found your tool and am very happy due to its ease in setup and maintenance. Just got 2 questions or better looking for recommendations:

1) Is it better to backup specific datasets or the whole pool. In your example you do both by setting autobackup:offsite1=true. Isn't that redundant, or is zfs_autobackup taking care for that.

2) inline with the distinction pool vs dataset backup, you specified autobackup:xxx=child in the proxmox cluster example. However, I did not find any description of the child parameter.

Thanks for the great software and for your help,

best, Florian

**Comment by psy0rz** [comment]
1. In the example i've set the property on the highest dataset, and it inherited by all child datasets. Essentially this makes a backup from the whole pool. I've updated the example to expain this a bit better. Its never redundant, no matter how you set it. See 
2. Good point..it seems i've never documented that. I've updated the documentation. (child only selects child-datasets, not the dataset itself)

Updated: https://github.com/psy0rz/zfs_autobackup/blob/master/README.md#select-filesystems-to-backup

Thanks for using zfs-autobackup, and let me know if you have more questions. :)
