### ISSUE TITLE
It says 'cannot receive incremental stream: destination has been modified since most recent snapshot'

### ISSUE THREAD

**Issue by bytec77** [psy0rz/zfs_autobackup#73]
Hi, 

got this issue on running Proxmox LXC containers. 

```bash
[Target] rpool/backup/prox220/subvol-117-disk-0@prox220-20210406203307: receiving incremental
! [Target] STDERR > cannot receive incremental stream: destination rpool/backup/prox220/subvol-117-disk-0 has been modified
! [Target] STDERR > since most recent snapshot
! [Source] rpool/data/subvol-117-disk-0: FAILED: Command '(pipe)' returned non-zero exit status 255.
```

```bash
zfs-autobackup --ssh-source 10.0.1.220 prox220 rpool/backup/prox220 --keep-source=3 --keep-target=31 --progress --verbose --strip-path 2 --destroy-missing 20d --rollback
```

the VMs and the not running LXC works fine.

**Comment by psy0rz** [comment]
strange..can you run it in --debug mode?

**Comment by bytec77** [comment]
ok I did some research. 

I destroyed all issued snaps on both sides and the datasets on the backup server. Then I start zfs-autobackup again and it works and pulls the full stream. 
After a while start it again and it works fine with pulling the incremental. 

Then I restart my Backup Proxmox and after starting zfs-autobackup it ran in the issue again.  

On the Backup Proxmox no LXC or VM is running.

**Comment by psy0rz** [comment]
On the target prox, did you configure a LXC to use that backup-dataset? (even tough its not running)

**Comment by bytec77** [comment]
No there are no lxc configured.

**Comment by psy0rz** [comment]
To work around you probably can destroy it again on the backup server and then use --clear-mountpoint. 

This way it wont get mounted. (in the wrong place perhaps) And the chance for changes is smaller.

**Comment by psy0rz** [comment]
The documentation on this was also wrong, i updated it: https://github.com/psy0rz/zfs_autobackup/blob/master/README.md#it-says-cannot-receive-incremental-stream-invalid-backup-stream

**Comment by bytec77** [comment]
Ok I will try that later.  But why does only a reboot make the problems.
Do you think zfs-auto-snapshot that is running on that machine but not in the dataset will have an effect? 

Von meinem iPhone gesendet

**Comment by psy0rz** [comment]
No that shouldn't have an effect. But ive had similar weird things on prox. Perhaps there is some deamon thats part of proxmox that does something with a dataset when its changed by us. (The dataset has to exist on reboot so the deamon will use/monitor it for example.)

**Comment by bytec77** [comment]
https://forum.proxmox.com/threads/zfs-error-cannot-destroy-dataset-is-busy.25811/page-2

Do you think this could cause the problems?

I must also tun zfs Release to destroy the Datasets on the Backup Server

**Comment by psy0rz** [comment]
Nope, thats something different. You can use --no-holds if you dont want zfs-autobackup to hold the snapshots. (Holding is only done to prevent accidental deletion or the common snapshot by the user)

**Comment by psy0rz** [comment]
Do you have the lastest proxmox updates on the target?

**Comment by bytec77** [comment]
Yes both systems on 6.3.6 updated yesterday

**Comment by psy0rz** [comment]
I'll try to check some stuff on a proxmox environment next week to see if i can reproduce the problem.

If anyone else has this problem as well, feel free to add comments.

**Comment by bytec77** [comment]
with --clear-mountpoint it seems to work. 

But it would be interesting what the error is.

**Comment by psy0rz** [comment]
nice!

to find out you might try it again without clear-mountpoint, and then do this:
```
zfs get mountpoint dataset
```
and see if the mountpoint where it wants to mount.

if its anything outside the backup-directory, that might be your problem. 

it might even be the same path as an existing lxc

**Comment by bytec77** [comment]
After I did what you said above (without --clear-mountpoint) I found out that no mountpoint for the dataset exists so zfs-autobackup works fine. 

When I run zfs mount -a the issue comes up again. So I think that proxmox do a zfs mount -a on reboot.

**Comment by psy0rz** [comment]
The canmount property of the recieved datasets should be set to noauto, if you use --clear-mountpoint.

**Comment by psy0rz** [comment]
see https://github.com/psy0rz/zfs_autobackup/wiki/Mounting
