### ISSUE TITLE
Thinning settings still printed when --no-thinning is set.

### ISSUE THREAD

**Issue by tpyro** [psy0rz/zfs_autobackup#74]
I am still getting this output (for both source & target) in spite of using the new --no-thinning option.

>  #### Target settings
>   [Target] Datasets on: xxxxxx
>   [Target] Keep the last 10 snapshots.
>   [Target] **Keep every 1 day, delete after 1 week.**
>   [Target] **Keep every 1 week, delete after 1 month.**
>   [Target] **Keep every 1 month, delete after 1 year**

**Comment by psy0rz** [comment]
Good point. It actually is skipping the actual thinning code, but this message is indeed still shown.

Thanks, i'll fix it
