### ISSUE TITLE
Type of incremental source could be specified to avoid warning

### ISSUE THREAD

**Issue by dmshimself** [psy0rz/zfs_autobackup#86]
I see warnings such as

! [Target] STDERR|> Warning: incremental source didn't specify type, assuming snapshot. Use '@' or '#' prefix to avoid ambiguity.

Everything seems to work fine, so I suspect this is currently a cosmetic error

**Comment by psy0rz** [comment]
This is fixed in 3.1.

**Comment by dmshimself** [comment]
Great news - many thanks
