### ISSUE TITLE
Make everything thats derived from backup_name configurable.

### ISSUE THREAD

**Issue by bagbag** [psy0rz/zfs_autobackup#87]
Hi,

my goal: have N-way sync.

Let's say we have 5 servers sharing a dataset and all of them are allowed to write to it. We assume that all servers ensure they don't write at the same time to avoid a conflict. Because zfs-autobackup doesn't create snapshots if a dataset or volume didn't change if we want it to, we can simply setup a snapshot-only job on each server (with the same name on all servers) to create a new snapshot when something has changed and use another pull job on all servers pulling from all others using `--no-snapshot` to fetch the changes. This should work fine until one of the servers doesn't pull (for whatever reason) for long enough for thinning to remove the snapshot it depend on. The problem is that all share the same job name and therefore the hold is removed and the snapshot destroyed, whenever any of the servers decide that it's time for thinning.

Why don't use another name for every pull-job on each server?
Because we have to set N properties on *every* server. In this example with 5 servers we already need 20 `autobackup:pull-$X=true` + 5 `autobackup:snapshot-only` in total. For 10 servers it would be 100. For every server we add, we have to go through all servers and add the required properties.

Proposed solution:
Add a parameter like `--hold-name` to change the name for the created and released holds, this way a single `autoback:regular-snapshot` on every server is enough.

Thanks for you awesome piece of software!

**Comment by psy0rz** [comment]
This would be a possible solution for your problem.

Another way would be to specifiy a parameter like --select-property, so every zfs-backup instance looks at the same property instead of autobackup:name, while still using their own snapshot names and hold names.

This way you can use the same property on all servers, without having any conflicts.

Maybe it would be wise to make both configurable, for different use cases?

**Comment by bagbag** [comment]
If we think that further, you should just make every aspect configurable.

property name to look at
snapshot prefix
holds name
..basically everything derived from the instance name

If you specify an instance name, all the names will be defaulted to the current values which you can overwrite with flags. If you don't specify a instance name, you have to specify all flags.

**Comment by psy0rz** [comment]
Yes i think thats the best way to go. It will be in the next version. (I just finally released 3.1) :)

**Comment by psy0rz** [comment]
I've made a few changes and added options to select the formatting of names.

In your case you should be fine with the --hold-format option. Let me know how it goes :)
