### ISSUE TITLE
multiple targets

### ISSUE THREAD

**Issue by feijoas** [psy0rz/zfs_autobackup#91]
How is `zfs-autobackup` supposed to be used with multiple targets with different keep policies?

For example, I would like to have 
- hourly snapshots of my system `zfs-autobackup label --keep-source 1h1d `
- send them to a second hdd `zfs-autobackup label hdd --keep-source 1h1d`
- send them to a long term storage  `zfs-autobackup label --ssh-target server1.server.com --keep-source 1h1d --keep-target 1d1y`

Do I have to repeat the `--keep-source 1h1d` every time? What happens if `--keep-source` is different?

**Comment by psy0rz** [comment]
Yes, zfs-autobackup analyses the situation every time you run it.

As soon as you speciifiy a different schedule for keep-source, it will delete what it thinks is obsolete according to the new schedule. 

For example: Say you have on year worth of daily snapshots with schedule 1d1y, and suddenly you change the schedule to 1m1y (keep monthly snapshots for year)

Now zfs-autobackup will only keep a monlthy of that past year and delete the rest.

However: It will always transfer the existing source snapshots that are still wanted on the target side first. This is why its important to also specify the --keep-target schedule if you're only making snapshots. (So it knows what it should keep for the target)

Also see: https://github.com/psy0rz/zfs_autobackup#thinning-out-obsolete-snapshots

**Comment by psy0rz** [comment]
I added a note the documentation to clear this up a bit further.

**Comment by feijoas** [comment]
Thanks for the answer and the great tool. I made a [PR](https://github.com/NixOS/nixpkgs/pull/135206) for NixOS.

**Comment by psy0rz** [comment]
Oh awesome, thanks!

Is it also possible to use pip in nixos?

**Comment by feijoas** [comment]
For developers, python support on NixOS is a work in progress and not a good user experience at the moment: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md

However, users will not notice any differences.

**Comment by psy0rz** [comment]
ah thanks :)
