### ISSUE TITLE
Starting over with new backup server

### ISSUE THREAD

**Issue by dmshimself** [psy0rz/zfs_autobackup#94]
My existing backup server no longer works, including the disks, so I've built a new one and reinstalled zfs_autobackup.

Are there some steps I should follow to tidy up the existing snapshots on the source so that I can run autobackup on the target without it thinking there are snapshots around?

**Comment by psy0rz** [comment]
No, you can just run zfs-autobackup and use the same backup-name.

zfs-autobackup will transfer all the existing source snapshots that are needed. (according to target-schedule)

There are no hidden states or extra properties you need to be aware of.

Use --test to see what will happen if you're not sure. :)

**Comment by dmshimself** [comment]
Many thanks - good to know!
