### ISSUE TITLE
cannot receive new filesystem stream: invalid backup stream

### ISSUE THREAD

**Issue by berenddeboer** [psy0rz/zfs_autobackup#99]
I'm attempting to backup a Ubuntu 21.04 pool ujsing zfs_autobackup in a jail inside latest TrueNas, but get this error:

```
  #### Synchronising
  [Source] tank/home/berend@offsite1-20210930113513: Destroying
  [Target] home/iocage/jails/autobackup-2021-09-30/data/tank/home/berend@offsite1-20210930111614: receiving full
! [Target] STDERR > cannot receive new filesystem stream: invalid backup stream
! [Source] Command "ssh bonobo 'zfs send --large-block --embed --verbose --parsable --props tank/home/berend@offsite1-20210930111614'" returned exit code 255 (valid codes: [0])
! [Target] Command "zfs recv -u -v -s home/iocage/jails/autobackup-2021-09-30/data/tank/home/berend" returned exit code 1 (valid codes: [0])
! [Source] tank/home/berend: FAILED: Last command returned error
! 1 dataset(s) failed!
```

TrueNas version: 12.0-U5.1 (FreeBSD 12.2-p9)

Ubuntu: 21.04

TrueNas pool is on latest (i.e. `zfs upgrade` doesn't upgrade). Same for Ubuntu.

Any ideas what could be going on?

**Comment by berenddeboer** [comment]
Redirecting to /dev/null indicates I can read the source:

```
zfs recv -u -v -s home/iocage/jails/autobackup-2021-09-30/data/tank/home/berend
```

**Comment by berenddeboer** [comment]
This might actually be a jails issue. I can create zfs datasets in this jail, so that works.

But when I try this outside the jail directly in TrueNAS it works:

```
# ssh 192.168.33.4 'zfs send --large-block --embed --verbose --parsable --props tank/home/berend@offsite1-20210930111614' | zfs recv -u -v -s home/iocage/jails/autobackup-2021-09-30/data/tank/home/berend
full    tank/home/berend@offsite1-20210930111614        333592844408
size    333592844408
receiving full stream of tank/home/berend@offsite1-20210930111614 into home/iocage/jails/autobackup-2021-09-30/data/tank/home/berend@offsite1-20210930111614
13:22:11        2232328 tank/home/berend@offsite1-20210930111614
13:22:12        8397360 tank/home/berend@offsite1-20210930111614
13:22:13        32440632        tank/home/berend@offsite1-20210930111614
13:22:14        56367688        tank/home/berend@offsite1-20210930111614
13:22:15        80843768        tank/home/berend@offsite1-20210930111614
13:22:16        105502664       tank/home/berend@offsite1-20210930111614
13:22:17        130671224       tank/home/berend@offsite1-20210930111614
13:22:18        155328512       tank/home/berend@offsite1-20210930111614
13:22:19        179581200       tank/home/berend@offsite1-20210930111614
13:22:20        204169952       tank/home/berend@offsite1-20210930111614
13:22:21        228778912       tank/home/berend@offsite1-20210930111614
```

Any ideas on how to make this work inside a jail? Installing stuff directly in TrueNAS seems to be a bad pattern.

**Comment by psy0rz** [comment]
It indeed seems a freebsd jails related issue. Perhaps try googling for it.

You also can use --debug so you can get the exact send/recv pipe command line. Then you can use that one to do some more manual testing and debugging. (run inside/outside, perhaps ajust some parameters)

Maybe there is something in dmesg.

Maybe its a permission issue with some kind of property thats received. So try removing the -p option from zfs send.

**Comment by Scrin** [comment]
Are you using ZFS native encryption or any other "new" ZFS features?

TrueNAS 12 ships with OpenZFS 2.0 despite being based on FreeBSD 12 which ships with an older ZFS implementation, and thus by default the jails are limited to that (or older). So to access such newer features from a jail you need to either get a newer version of ZFS (such as OpenZFS 2.0) to work inside the jail (not entirely sure if it's even trivially possible), or wait for a future TrueNAS version that's based on FreeBSD 13 which natively ships with OpenZFS 2.0 (and thus you can use FreeBSD 13 based jails with OpenZFS 2.0 out-of-the-box)

**Comment by berenddeboer** [comment]
@Scrin not using native ZFS encryption yet. Not sure about other features, quite probably not.

**Comment by berenddeboer** [comment]
@psy0rz: it works outside of the jail, not inside. So seems like a FreeBSD jails issue, not zfs_autobackup. Removing `--props` didn't help. Perhaps it's a permission issue? `zfs recv` not allowed in jails??

**Comment by Scrin** [comment]
`zfs recv` is allowed in jails, although it is possible to restrict it. You can try creating datasets with `zfs create` inside the jail and those should work even with mismatched versions, as merely creating a dataset is not (normally) touching any of the newer features. It is also possible that the pool is using some of the newer features without you knowing, for example if you have created the pool on TrueNAS 12.x.

You can see the version mismatch yourself for example by trying `zfs get compression` and `zfs get encryption` inside and outside of the jail. The compression property, which is an old feature by now, should be readable both inside and outside of the jail with no issues, but if the encryption one, being a new feature, works outside of the jail but inside it complains about it not being a supported property, you have this version mismatch.

Someone did post [a (dirty) workaround in the TrueNAS jira](https://jira.ixsystems.com/browse/NAS-108832?focusedCommentId=126171&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-126171) which copies the (OpenZFS) binaries and libraries from the host into the jail which you may try if you feel adventurous, but I have not tested this myself. I did run into this same issue a while ago myself and I decided to wait for an official update to get OpenZFS 2.0 into the jails - until then my own workaround is to mount a iSCSI block share from TrueNAS into a "backupper" virtual machine that runs zfs_autobackup.

**Comment by berenddeboer** [comment]
`zfs create` works inside the jail, but obviously I can only create a dataset which is part of my jailed dataset. So did `zfs create home/iocage/jails/autobackup-2021-09-30/data/tmp` but `zfs recv` to that dataset still failed.

But yes, my source zfs is zfs 2 (Ubuntu 21.04), that might have something to do with it. I also tried to make a backup of a directory of the FreeNAS host to the jail, but failed to, but as you pointed out, that's ZFS 2 as well.

I created another FreeBSD 12.2 jail, and tried to use zfs_autobackup on that, but that failed as well. Which is slightly odd as the zfs versions are the same (but the underlying zfs is TrueNAS still).

**Comment by Scrin** [comment]
Yeah that sounds about right. The reason why the jail-to-jail test fails is because even though you're creating the datasets inside the jail using older version binaries, the actual syscalls that the binaries make to the kernel are still going to the zfs kernel module on the host (since the jails are just jails for isolation, not actual virtual machines with their own running kernel) so the datasets are still created by the kernel module on the host to the pool with all the "new features" already available. The kernel module likely doesn't even know the calls come from older binaries. Thus effectively this is not that much different from creating the datasets on the host directly using the new version binaries on the host.

If you were to create a "old version" ZFS pool somehow and avoid doing a zpool upgrade on it, then in theory it should work from the jail as well (or any source really) since the sent stream would be of an older version that the binaries in the jail understand when reading the stream during recv. Although even if this works, I wouldn't recommend it as it's rather hacky to depend on *not* updating something. This is about as much as I know regarding this issue after my investigations a while back when I ran into this issue when I was upgrading my storage infrastructure, and I did not find any other reliable workaround that I'd dare to run in production. However if you happen to find a reliable workaround I'd be very happy to hear about it

**Comment by berenddeboer** [comment]
Absolutely brilliant @Scrin, you were spot on. After I copied the `zfs` binary, and a couple of libraries from TrueNAS host to the jail, it worked!

For others: I just copied `zfs`, then copied all the libraries it complained about missing, one by one, until it worked. Just 4 libraries.

**Comment by Scrin** [comment]
Nice to hear that trick worked! The person over at the TrueNAS jira never replied back whether that worked well enough so I never bothered testing it. I might even try that in my setup as well at some point, since it may take a while until TrueNAS gets an update based on FreeBSD 13 (or any other workaround to get FreeBSD 13 jails). If you end up using this trick "in production", I'd appreciate a headsup if you run into any issues later

**Comment by psy0rz** [comment]
allright, nice you guy solved it! :)

**Comment by lapo-luchini** [comment]
> For others: I just copied `zfs`, then copied all the libraries it complained about missing, one by one, until it worked. Just 4 libraries.

Just for completeness:

```bash
cp /usr/local/sbin/zfs /mnt/tank/iocage/jails/JAILNAME/root/sbin/
cp /usr/local/lib/libzfs.so.4 /mnt/tank/iocage/jails/JAILNAME/root/usr/lib/
cp /usr/local/lib/libzfs_core.so.3 /mnt/tank/iocage/jails/JAILNAME/root/usr/lib/
cp /usr/local/lib/libnvpair.so.3 /mnt/tank/iocage/jails/JAILNAME/root/usr/lib/
cp /usr/local/lib/libuutil.so.3 /mnt/tank/iocage/jails/JAILNAME/root/usr/lib/
cp /usr/local/lib/libintl.so.8 /mnt/tank/iocage/jails/JAILNAME/root/usr/lib/
```

**Comment by vauxia** [comment]
I solved the same issue by installing the `openzfs-2021040600` package inside of the jail using `pkg.` This is how zfs is installed in the host/TrueNAS environment and will help ensure that the binaries are correct going forward. It's not necessary to install the openzfs-kmod module inside of the jail.

You need to get rid of /usr/sbin/zfs to avoid conflicts. You can maybe just delete these but I replaced them with a hard link their /usr/local/sbin/ counterparts.
